/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin-api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_admin_api_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_admin_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/auth/mfa/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mfa Confirm */
    post: operations['mfa_confirm_admin_api_auth_mfa_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/auth/mfa/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mfa Setup */
    post: operations['mfa_setup_admin_api_auth_mfa_setup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/auth/mfa/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mfa Verify */
    post: operations['mfa_verify_admin_api_auth_mfa_verify_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/auth/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Current Session
     * @description Lets the admin UI restore its CSRF token after a page reload.
     */
    get: operations['current_session_admin_api_auth_session_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/impersonations/{impersonation_id}/end': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End Impersonation */
    post: operations['end_impersonation_admin_api_impersonations__impersonation_id__end_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/impersonations/{impersonation_id}/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Impersonation Summary */
    get: operations['impersonation_summary_admin_api_impersonations__impersonation_id__summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/tenants': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Tenants */
    get: operations['list_tenants_admin_api_tenants_get']
    put?: never
    /** Create Tenant */
    post: operations['create_tenant_admin_api_tenants_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/tenants/{tenant_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Tenant */
    patch: operations['update_tenant_admin_api_tenants__tenant_id__patch']
    trace?: never
  }
  '/admin-api/tenants/{tenant_id}/impersonations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Impersonate */
    post: operations['impersonate_admin_api_tenants__tenant_id__impersonations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/tenants/{tenant_id}/modules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Modules */
    put: operations['put_modules_admin_api_tenants__tenant_id__modules_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/tenants/{tenant_id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Change Status */
    put: operations['change_status_admin_api_tenants__tenant_id__status_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin-api/tenants/{tenant_id}/subscription': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Subscription */
    put: operations['put_subscription_admin_api_tenants__tenant_id__subscription_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness plus database status (NFR-010). 503 lets uptime checks and Docker see an outage.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AdminSessionOut */
    AdminSessionOut: {
      /** Csrf Token */
      csrf_token: string
      /** Email */
      email: string
      /** Mfa State */
      mfa_state: string
      /** Role */
      role: string
    }
    /** CodeIn */
    CodeIn: {
      /** Code */
      code: string
    }
    /** Created */
    Created: {
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** ImpersonationIn */
    ImpersonationIn: {
      /**
       * Minutes
       * @default 30
       */
      minutes: number
      /** Reason */
      reason: string
    }
    /** ImpersonationOut */
    ImpersonationOut: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** LoginIn */
    LoginIn: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** ModulesIn */
    ModulesIn: {
      /** Modules */
      modules: string[]
    }
    /** SetupOut */
    SetupOut: {
      /** Otpauth Uri */
      otpauth_uri: string
      /** Secret */
      secret: string
    }
    /** StatusIn */
    StatusIn: {
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'suspended' | 'deleted'
    }
    /** SubscriptionIn */
    SubscriptionIn: {
      /** Ends At */
      ends_at: string | null
      /** Grace Days */
      grace_days: number
      /**
       * Plan Type
       * @enum {string}
       */
      plan_type: 'free' | 'paid'
      /** Reminder Days */
      reminder_days: number[]
      /** Reminders Enabled */
      reminders_enabled: boolean
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string
    }
    /** TenantCreate */
    TenantCreate: {
      /**
       * Country
       * @default ID
       */
      country: string
      /**
       * Currency
       * @default IDR
       */
      currency: string
      /** Ends At */
      ends_at?: string | null
      /**
       * Language
       * @default id
       */
      language: string
      /** Legal Name */
      legal_name: string
      /** Name */
      name: string
      /** Owner Email */
      owner_email: string
      /**
       * Plan Type
       * @default free
       * @enum {string}
       */
      plan_type: 'free' | 'paid'
      /**
       * Profile
       * @enum {string}
       */
      profile: 'restaurant' | 'cloud_kitchen' | 'central_kitchen_group' | 'hybrid'
      /**
       * Timezone
       * @default Asia/Jakarta
       */
      timezone: string
    }
    /** TenantOut */
    TenantOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Modules */
      modules: string[]
      /** Name */
      name: string
      /** Profile */
      profile: string
      /** Status */
      status: string
      /** Subscription State */
      subscription_state: string | null
    }
    /** TenantUpdate */
    TenantUpdate: {
      /** Language */
      language?: string | null
      /** Legal Name */
      legal_name?: string | null
      /** Name */
      name?: string | null
      /** Profile */
      profile?: ('restaurant' | 'cloud_kitchen' | 'central_kitchen_group' | 'hybrid') | null
      /** Timezone */
      timezone?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** ViewAudit */
    ViewAudit: {
      /** Action */
      action: string
      /** Actor Type */
      actor_type: string
      /**
       * At
       * Format: date-time
       */
      at: string
    }
    /** ViewOutlet */
    ViewOutlet: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Type */
      type: string
    }
    /** ViewSummary */
    ViewSummary: {
      /** Members */
      members: number
      /** Outlets */
      outlets: components['schemas']['ViewOutlet'][]
      /** Recent Audit */
      recent_audit: components['schemas']['ViewAudit'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login_admin_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminSessionOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_admin_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  mfa_confirm_admin_api_auth_mfa_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CodeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminSessionOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  mfa_setup_admin_api_auth_mfa_setup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SetupOut']
        }
      }
    }
  }
  mfa_verify_admin_api_auth_mfa_verify_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CodeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminSessionOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  current_session_admin_api_auth_session_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminSessionOut']
        }
      }
    }
  }
  end_impersonation_admin_api_impersonations__impersonation_id__end_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        impersonation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  impersonation_summary_admin_api_impersonations__impersonation_id__summary_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        impersonation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ViewSummary']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_tenants_admin_api_tenants_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TenantOut'][]
        }
      }
    }
  }
  create_tenant_admin_api_tenants_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TenantCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Created']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_tenant_admin_api_tenants__tenant_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        tenant_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TenantUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  impersonate_admin_api_tenants__tenant_id__impersonations_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        tenant_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ImpersonationIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ImpersonationOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_modules_admin_api_tenants__tenant_id__modules_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        tenant_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ModulesIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  change_status_admin_api_tenants__tenant_id__status_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        tenant_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_subscription_admin_api_tenants__tenant_id__subscription_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        tenant_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubscriptionIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
