/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/alert-rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Alert Rules */
    get: operations['list_alert_rules_api_v1_alert_rules_get']
    put?: never
    /** Create Alert Rule */
    post: operations['create_alert_rule_api_v1_alert_rules_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/alert-rules/{rule_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Alert Rule */
    delete: operations['delete_alert_rule_api_v1_alert_rules__rule_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/approval-rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Approval Rules */
    get: operations['list_approval_rules_api_v1_approval_rules_get']
    put?: never
    /** Create Approval Rule */
    post: operations['create_approval_rule_api_v1_approval_rules_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/approval-rules/{rule_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Approval Rule */
    delete: operations['delete_approval_rule_api_v1_approval_rules__rule_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/invitations/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Accept Invitation
     * @description New email: creates the account with the given password. Existing account: the
     *     password must match it (proves the invitee owns that account). Then sign in normally.
     */
    post: operations['accept_invitation_api_v1_auth_invitations_accept_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mfa Confirm
     * @description Finish enrolment with a first code from the app; returns recovery codes once.
     */
    post: operations['mfa_confirm_api_v1_auth_mfa_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mfa Setup
     * @description Start (or restart) enrolment. Allowed when fully signed in or when enrolment is
     *     required; not while a code is still owed for an existing setup.
     */
    post: operations['mfa_setup_api_v1_auth_mfa_setup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mfa Verify
     * @description Second sign-in step: a TOTP code, or a one-time recovery code.
     */
    post: operations['mfa_verify_api_v1_auth_mfa_verify_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password-reset/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm Password Reset
     * @description Single use; sets the new password and signs the user out everywhere. 2FA still
     *     applies at the next sign-in, so a stolen mailbox alone cannot take over an owner.
     */
    post: operations['confirm_password_reset_api_v1_auth_password_reset_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password-reset/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request Password Reset
     * @description Always 202, whether or not the email has an account (no account enumeration).
     */
    post: operations['request_password_reset_api_v1_auth_password_reset_request_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current Session */
    get: operations['current_session_api_v1_auth_session_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * My Sessions
     * @description FR-IDN-007: the user's active sessions, newest activity first.
     */
    get: operations['my_sessions_api_v1_auth_sessions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/sessions/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Revoke Session
     * @description FR-IDN-007: revoke one of your own sessions (404 for anyone else's).
     */
    delete: operations['revoke_session_api_v1_auth_sessions__session_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/switch-tenant': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Switch Tenant
     * @description FR-IDN-005. The requested tenant is only a choice: it is checked against the user's
     *     memberships. The session is rotated (new token and CSRF token) because the privileges
     *     change, which defeats session fixation.
     */
    post: operations['switch_tenant_api_v1_auth_switch_tenant_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/boms/{bom_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Bom */
    get: operations['get_bom_api_v1_catalog_boms__bom_id__get']
    /** Update Draft */
    put: operations['update_draft_api_v1_catalog_boms__bom_id__put']
    post?: never
    /** Delete Draft */
    delete: operations['delete_draft_api_v1_catalog_boms__bom_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/boms/{bom_id}/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Activate */
    post: operations['activate_api_v1_catalog_boms__bom_id__activate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Categories */
    get: operations['list_categories_api_v1_catalog_categories_get']
    put?: never
    /** Create Category */
    post: operations['create_category_api_v1_catalog_categories_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/categories/{category_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Category */
    put: operations['update_category_api_v1_catalog_categories__category_id__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/channels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Channels */
    get: operations['list_channels_api_v1_catalog_channels_get']
    put?: never
    /** Create Channel */
    post: operations['create_channel_api_v1_catalog_channels_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/channels/{channel_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Channel */
    put: operations['update_channel_api_v1_catalog_channels__channel_id__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Items */
    get: operations['list_items_api_v1_catalog_items_get']
    put?: never
    /** Create Item */
    post: operations['create_item_api_v1_catalog_items_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/items/{item_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Item */
    get: operations['get_item_api_v1_catalog_items__item_id__get']
    /** Update Item */
    put: operations['update_item_api_v1_catalog_items__item_id__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/items/{item_id}/boms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Versions */
    get: operations['list_versions_api_v1_catalog_items__item_id__boms_get']
    put?: never
    /** Create Draft */
    post: operations['create_draft_api_v1_catalog_items__item_id__boms_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/items/{item_id}/costing': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Item Costing */
    get: operations['item_costing_api_v1_catalog_items__item_id__costing_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/items/{item_id}/prices': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Price History */
    get: operations['price_history_api_v1_catalog_items__item_id__prices_get']
    /** Set Price */
    put: operations['set_price_api_v1_catalog_items__item_id__prices_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/prices': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Effective Prices */
    get: operations['effective_prices_api_v1_catalog_prices_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/prices/{price_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Price */
    delete: operations['delete_price_api_v1_catalog_prices__price_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/catalog/units': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Units */
    get: operations['list_units_api_v1_catalog_units_get']
    put?: never
    /** Create Unit */
    post: operations['create_unit_api_v1_catalog_units_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/adjustments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Adjustment */
    post: operations['create_adjustment_api_v1_inventory_adjustments_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/adjustments/{doc_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Adjustment */
    put: operations['update_adjustment_api_v1_inventory_adjustments__doc_id__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/adjustments/{doc_id}/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Adjustment */
    post: operations['submit_adjustment_api_v1_inventory_adjustments__doc_id__submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/adjustments/{doc_id}/{decision}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Decide Adjustment */
    post: operations['decide_adjustment_api_v1_inventory_adjustments__doc_id___decision__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/counts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Count */
    post: operations['start_count_api_v1_inventory_counts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/counts/{doc_id}/lines': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Enter Counted */
    put: operations['enter_counted_api_v1_inventory_counts__doc_id__lines_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/counts/{doc_id}/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Count */
    post: operations['submit_count_api_v1_inventory_counts__doc_id__submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/counts/{doc_id}/{decision}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Decide Count */
    post: operations['decide_count_api_v1_inventory_counts__doc_id___decision__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/documents/{kind}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Documents */
    get: operations['list_documents_api_v1_inventory_documents__kind__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/documents/{kind}/{doc_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Document */
    get: operations['get_document_api_v1_inventory_documents__kind___doc_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/movements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Movement History */
    get: operations['movement_history_api_v1_inventory_movements_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/opening': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Post Opening */
    post: operations['post_opening_api_v1_inventory_opening_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/opening/{doc_id}/reverse': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reverse Opening */
    post: operations['reverse_opening_api_v1_inventory_opening__doc_id__reverse_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/stock': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Stock */
    get: operations['stock_api_v1_inventory_stock_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/stock/{item_id}/batches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Item Batches */
    get: operations['item_batches_api_v1_inventory_stock__item_id__batches_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/valuation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Stock Valuation */
    get: operations['stock_valuation_api_v1_inventory_valuation_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/waste': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Post Waste */
    post: operations['post_waste_api_v1_inventory_waste_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/inventory/waste/{doc_id}/reverse': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reverse Waste */
    post: operations['reverse_waste_api_v1_inventory_waste__doc_id__reverse_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invitations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Invitation
     * @description FR-IDN-006: invite a person by email (single use, expiring link).
     */
    post: operations['create_invitation_api_v1_invitations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/capabilities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Capabilities
     * @description What the UI may show. Convenience only: every route re-checks on the server.
     */
    get: operations['capabilities_api_v1_me_capabilities_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/outlets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Outlets */
    get: operations['list_outlets_api_v1_outlets_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/outlets/{outlet_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Outlet
     * @description Another tenant's outlet is invisible (RLS); one outside the caller's scope is 404 too.
     */
    get: operations['get_outlet_api_v1_outlets__outlet_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/roles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Roles
     * @description The tenant's own roles (templates with tenant_id NULL are excluded).
     */
    get: operations['list_roles_api_v1_roles_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** All Settings */
    get: operations['all_settings_api_v1_settings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Setting */
    put: operations['put_setting_api_v1_settings__key__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness plus database status (NFR-010). 503 lets uptime checks and Docker see an outage.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AdjustmentIn */
    AdjustmentIn: {
      /**
       * Business Date
       * Format: date
       */
      business_date: string
      /** Lines */
      lines: components['schemas']['AdjustmentLineIn'][]
      /** Note */
      note?: string | null
      /**
       * Outlet Id
       * Format: uuid
       */
      outlet_id: string
      /**
       * Reason Code
       * @enum {string}
       */
      reason_code: 'correction' | 'found' | 'theft' | 'damaged' | 'other'
    }
    /** AdjustmentLineIn */
    AdjustmentLineIn: {
      /** Expiry Date */
      expiry_date?: string | null
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Qty */
      qty: number | string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
    }
    /** AlertRuleIn */
    AlertRuleIn: {
      /**
       * Alert Type
       * @enum {string}
       */
      alert_type:
        | 'below_reorder_point'
        | 'low_days_of_inventory'
        | 'batch_near_expiry'
        | 'expired_stock'
        | 'negative_stock'
        | 'count_variance'
        | 'food_cost_above_target'
        | 'approval_requested'
      /**
       * Channel
       * @default in_app
       * @enum {string}
       */
      channel: 'in_app' | 'email'
      /** Recipient Role Id */
      recipient_role_id?: string | null
      /** Recipient User Id */
      recipient_user_id?: string | null
    }
    /** AlertRuleOut */
    AlertRuleOut: {
      /**
       * Alert Type
       * @enum {string}
       */
      alert_type:
        | 'below_reorder_point'
        | 'low_days_of_inventory'
        | 'batch_near_expiry'
        | 'expired_stock'
        | 'negative_stock'
        | 'count_variance'
        | 'food_cost_above_target'
        | 'approval_requested'
      /**
       * Channel
       * @default in_app
       * @enum {string}
       */
      channel: 'in_app' | 'email'
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Recipient Role Id */
      recipient_role_id?: string | null
      /** Recipient User Id */
      recipient_user_id?: string | null
    }
    /**
     * AllSettings
     * @description Response of GET /settings, typed so the generated frontend client knows every field.
     */
    AllSettings: {
      numbering: components['schemas']['NumberingSettings']
      payment_methods: components['schemas']['PaymentMethodSettings']
      service_charge: components['schemas']['ServiceChargeSettings']
      session: components['schemas']['SessionSettings']
      stock: components['schemas']['StockSettings']
      tax: components['schemas']['TaxSettings']
    }
    /** ApprovalRuleIn */
    ApprovalRuleIn: {
      /**
       * Approver Role Id
       * Format: uuid
       */
      approver_role_id: string
      /**
       * Document Type
       * @enum {string}
       */
      document_type:
        | 'purchase_order'
        | 'transfer'
        | 'adjustment'
        | 'count'
        | 'void'
        | 'refund'
        | 'discount'
        | 'journal'
      /** Min Amount */
      min_amount: number
      /** Outlet Id */
      outlet_id?: string | null
    }
    /** ApprovalRuleOut */
    ApprovalRuleOut: {
      /**
       * Approver Role Id
       * Format: uuid
       */
      approver_role_id: string
      /**
       * Document Type
       * @enum {string}
       */
      document_type:
        | 'purchase_order'
        | 'transfer'
        | 'adjustment'
        | 'count'
        | 'void'
        | 'refund'
        | 'discount'
        | 'journal'
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Min Amount */
      min_amount: number
      /** Outlet Id */
      outlet_id?: string | null
    }
    /** BatchOut */
    BatchOut: {
      /** Expiry Date */
      expiry_date: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Lot Code */
      lot_code: string | null
      /** Qty */
      qty: string
      /**
       * Received At
       * Format: date-time
       */
      received_at: string
    }
    /** BomActivate */
    BomActivate: {
      /**
       * Valid From
       * Format: date
       */
      valid_from: string
    }
    /**
     * BomIn
     * @description A draft. Yield defaults to 1 base unit of the item (what a menu item needs).
     */
    BomIn: {
      /** Lines */
      lines: components['schemas']['BomLineIn'][]
      /** Yield Qty */
      yield_qty?: number | string | null
      /** Yield Unit Id */
      yield_unit_id?: string | null
    }
    /** BomLineIn */
    BomLineIn: {
      /**
       * Component Item Id
       * Format: uuid
       */
      component_item_id: string
      /** Qty */
      qty: number | string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
      /**
       * Waste Pct
       * @default 0
       */
      waste_pct: number | string
    }
    /** BomLineOut */
    BomLineOut: {
      /**
       * Component Item Id
       * Format: uuid
       */
      component_item_id: string
      /** Component Name */
      component_name: string
      /** Component Sku */
      component_sku: string
      /** Qty */
      qty: string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
      /** Waste Pct */
      waste_pct: string
    }
    /** BomOut */
    BomOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Lines */
      lines: components['schemas']['BomLineOut'][]
      /**
       * Status
       * @enum {string}
       */
      status: 'draft' | 'active'
      /** Valid From */
      valid_from: string | null
      /** Valid To */
      valid_to: string | null
      /** Version */
      version: number
      /** Yield Qty */
      yield_qty: string
      /**
       * Yield Unit Id
       * Format: uuid
       */
      yield_unit_id: string
    }
    /** BomSummary */
    BomSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'draft' | 'active'
      /** Valid From */
      valid_from: string | null
      /** Valid To */
      valid_to: string | null
      /** Version */
      version: number
      /** Yield Qty */
      yield_qty: string
      /**
       * Yield Unit Id
       * Format: uuid
       */
      yield_unit_id: string
    }
    /** Capabilities */
    Capabilities: {
      /** All Outlets */
      all_outlets: boolean
      /** Currency */
      currency: string
      /** Language */
      language: string
      /** Modules */
      modules: string[]
      /** Nav */
      nav: string[]
      /** Outlet Ids */
      outlet_ids: string[]
      /** Permissions */
      permissions: string[]
      subscription: components['schemas']['SubscriptionBanner']
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string
    }
    /** CategoryIn */
    CategoryIn: {
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
      /** Name */
      name: string
      /** Parent Id */
      parent_id?: string | null
      /**
       * Sort Order
       * @default 0
       */
      sort_order: number
    }
    /** CategoryOut */
    CategoryOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
      /** Name */
      name: string
      /** Parent Id */
      parent_id?: string | null
      /**
       * Sort Order
       * @default 0
       */
      sort_order: number
    }
    /** ChannelIn */
    ChannelIn: {
      /** Code */
      code: string
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
      /**
       * Kind
       * @enum {string}
       */
      kind: 'dine_in' | 'takeaway' | 'platform' | 'wholesale'
      /** Name */
      name: string
      /** Platform */
      platform?: string | null
      /**
       * Sort Order
       * @default 0
       */
      sort_order: number
    }
    /** ChannelMargin */
    ChannelMargin: {
      /**
       * Channel Id
       * Format: uuid
       */
      channel_id: string
      /** Cost Pct */
      cost_pct: string | null
      /** Margin */
      margin: string | null
      /** Net Price */
      net_price: number
      /** Price */
      price: number
    }
    /** ChannelOut */
    ChannelOut: {
      /** Code */
      code: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
      /**
       * Kind
       * @enum {string}
       */
      kind: 'dine_in' | 'takeaway' | 'platform' | 'wholesale'
      /** Name */
      name: string
      /** Platform */
      platform?: string | null
      /**
       * Sort Order
       * @default 0
       */
      sort_order: number
    }
    /** CodeRequest */
    CodeRequest: {
      /** Code */
      code: string
    }
    /** ConversionIn */
    ConversionIn: {
      /** Factor To Base */
      factor_to_base: number | string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
    }
    /** ConversionOut */
    ConversionOut: {
      /** Factor To Base */
      factor_to_base: string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
    }
    /**
     * CostLine
     * @description One ingredient after expanding nested recipes, per 1 base unit of the item.
     */
    CostLine: {
      /** Base Qty */
      base_qty: string
      /** Cost */
      cost: string | null
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Name */
      name: string
      /** Sku */
      sku: string
      /** Unit Code */
      unit_code: string
      /** Unit Cost */
      unit_cost: string | null
    }
    /** Costing */
    Costing: {
      /** Bom Id */
      bom_id: string | null
      /** Cost */
      cost: string | null
      /** Cost Visible */
      cost_visible: boolean
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Lines */
      lines: components['schemas']['CostLine'][]
      /** Margins */
      margins: components['schemas']['ChannelMargin'][]
      /** Missing Costs */
      missing_costs: string[]
      /**
       * On
       * Format: date
       */
      on: string
    }
    /**
     * CountIn
     * @description Full: every item with stock at the outlet, plus `item_ids`. Spot and cycle: only
     *     `item_ids`. Blind: counters do not see the system quantity.
     */
    CountIn: {
      /**
       * Blind
       * @default false
       */
      blind: boolean
      /**
       * Business Date
       * Format: date
       */
      business_date: string
      /**
       * Count Type
       * @enum {string}
       */
      count_type: 'full' | 'spot' | 'cycle'
      /** Item Ids */
      item_ids?: string[]
      /** Note */
      note?: string | null
      /**
       * Outlet Id
       * Format: uuid
       */
      outlet_id: string
    }
    /** CountedIn */
    CountedIn: {
      /** Lines */
      lines: components['schemas']['CountedLine'][]
    }
    /** CountedLine */
    CountedLine: {
      /** Counted Qty */
      counted_qty: number | string
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
    }
    /** DocLine */
    DocLine: {
      /** Counted Qty */
      counted_qty?: string | null
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Name */
      name: string
      /** Qty */
      qty?: string | null
      /** Sku */
      sku: string
      /** System Qty */
      system_qty?: string | null
      /** Unit Code */
      unit_code: string
      /** Unit Id */
      unit_id?: string | null
    }
    /** EffectivePrice */
    EffectivePrice: {
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Price */
      price: number
      /**
       * Valid From
       * Format: date
       */
      valid_from: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** InvitationAccept */
    InvitationAccept: {
      /** Name */
      name?: string | null
      /** Password */
      password: string
      /** Token */
      token: string
    }
    /** InvitationCreate */
    InvitationCreate: {
      /** Email */
      email: string
      /**
       * Role Id
       * Format: uuid
       */
      role_id: string
    }
    /** InvitationOut */
    InvitationOut: {
      /** Email */
      email: string
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** ItemIn */
    ItemIn: {
      /** Allergens */
      allergens?: string[]
      /**
       * Base Unit Id
       * Format: uuid
       */
      base_unit_id: string
      /** Category Id */
      category_id?: string | null
      /** Conversions */
      conversions?: components['schemas']['ConversionIn'][]
      /**
       * Is Stocked
       * @default true
       */
      is_stocked: boolean
      /** Shelf Life Days */
      shelf_life_days?: number | null
      /** Sku */
      sku: string
      /** Storage Type */
      storage_type?: ('frozen' | 'chilled' | 'dry') | null
      /** Translations */
      translations: components['schemas']['TranslationIn'][]
      /**
       * Type
       * @enum {string}
       */
      type: 'ingredient' | 'semi_finished' | 'menu'
    }
    /** ItemOut */
    ItemOut: {
      /** Allergens */
      allergens: string[]
      /**
       * Base Unit Id
       * Format: uuid
       */
      base_unit_id: string
      /** Category Id */
      category_id: string | null
      /** Conversions */
      conversions: components['schemas']['ConversionOut'][]
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Active */
      is_active: boolean
      /** Is Stocked */
      is_stocked: boolean
      /** Name */
      name: string
      /** Shelf Life Days */
      shelf_life_days: number | null
      /** Sku */
      sku: string
      /** Storage Type */
      storage_type: string | null
      /** Translations */
      translations: components['schemas']['TranslationOut'][]
      /**
       * Type
       * @enum {string}
       */
      type: 'ingredient' | 'semi_finished' | 'menu'
      /** Version */
      version: number
    }
    /** ItemSummary */
    ItemSummary: {
      /**
       * Base Unit Id
       * Format: uuid
       */
      base_unit_id: string
      /** Category Id */
      category_id: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Active */
      is_active: boolean
      /** Name */
      name: string
      /** Sku */
      sku: string
      /**
       * Type
       * @enum {string}
       */
      type: 'ingredient' | 'semi_finished' | 'menu'
    }
    /** ItemUpdate */
    ItemUpdate: {
      /** Allergens */
      allergens?: string[]
      /**
       * Base Unit Id
       * Format: uuid
       */
      base_unit_id: string
      /** Category Id */
      category_id?: string | null
      /** Conversions */
      conversions?: components['schemas']['ConversionIn'][]
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
      /**
       * Is Stocked
       * @default true
       */
      is_stocked: boolean
      /** Shelf Life Days */
      shelf_life_days?: number | null
      /** Sku */
      sku: string
      /** Storage Type */
      storage_type?: ('frozen' | 'chilled' | 'dry') | null
      /** Translations */
      translations: components['schemas']['TranslationIn'][]
      /**
       * Type
       * @enum {string}
       */
      type: 'ingredient' | 'semi_finished' | 'menu'
      /** Version */
      version: number
    }
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** MfaSetupOut */
    MfaSetupOut: {
      /** Otpauth Uri */
      otpauth_uri: string
      /** Secret */
      secret: string
    }
    /** MovementOut */
    MovementOut: {
      /** Batch Id */
      batch_id: string | null
      /**
       * Business Date
       * Format: date
       */
      business_date: string
      /**
       * Doc Id
       * Format: uuid
       */
      doc_id: string
      /** Doc Type */
      doc_type: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Movement Type */
      movement_type: string
      /**
       * Posted At
       * Format: date-time
       */
      posted_at: string
      /** Qty */
      qty: string
      /** Reverses Id */
      reverses_id: string | null
      /** Unit Cost */
      unit_cost: string | null
      /** Value */
      value: number | null
    }
    /**
     * NegativeStockPolicy
     * @description FR-INV-006: what happens when more is used than is on hand. "warn": the user must
     *     confirm; "allow": posted and flagged for review; "block": refused.
     */
    NegativeStockPolicy: {
      /**
       * Other
       * @default block
       * @enum {string}
       */
      other: 'allow' | 'warn' | 'block'
      /**
       * Production
       * @default warn
       * @enum {string}
       */
      production: 'allow' | 'warn' | 'block'
      /**
       * Sale
       * @default allow
       * @enum {string}
       */
      sale: 'allow' | 'warn' | 'block'
      /**
       * Transfer
       * @default warn
       * @enum {string}
       */
      transfer: 'allow' | 'warn' | 'block'
    }
    /** NumberingFormat */
    NumberingFormat: {
      /**
       * Padding
       * @default 5
       */
      padding: number
      /** Prefix */
      prefix: string
      /**
       * Reset
       * @default yearly
       * @enum {string}
       */
      reset: 'yearly' | 'never'
    }
    /**
     * NumberingSettings
     * @description FR-TEN-009: per document type; numbers are allocated per outlet and year.
     */
    NumberingSettings: {
      /** Formats */
      formats?: {
        [key: string]: components['schemas']['NumberingFormat']
      }
    }
    /** OpeningIn */
    OpeningIn: {
      /**
       * Business Date
       * Format: date
       */
      business_date: string
      /** Lines */
      lines: components['schemas']['OpeningLine'][]
      /**
       * Outlet Id
       * Format: uuid
       */
      outlet_id: string
    }
    /**
     * OpeningLine
     * @description Stock counted when starting with the system. Quantity and cost per `unit_id`.
     */
    OpeningLine: {
      /** Expiry Date */
      expiry_date?: string | null
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Lot Code */
      lot_code?: string | null
      /** Qty */
      qty: number | string
      /** Unit Cost */
      unit_cost: number | string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
    }
    /** OutletOut */
    OutletOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Active */
      is_active: boolean
      /** Name */
      name: string
      /** Timezone */
      timezone: string
      /** Type */
      type: string
    }
    /** Page[EffectivePrice] */
    Page_EffectivePrice_: {
      /** Items */
      items: components['schemas']['EffectivePrice'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Page[ItemSummary] */
    Page_ItemSummary_: {
      /** Items */
      items: components['schemas']['ItemSummary'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Page[MovementOut] */
    Page_MovementOut_: {
      /** Items */
      items: components['schemas']['MovementOut'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Page[StockRow] */
    Page_StockRow_: {
      /** Items */
      items: components['schemas']['StockRow'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Page[ValuationRow] */
    Page_ValuationRow_: {
      /** Items */
      items: components['schemas']['ValuationRow'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** PasswordResetConfirm */
    PasswordResetConfirm: {
      /** New Password */
      new_password: string
      /** Token */
      token: string
    }
    /** PasswordResetRequest */
    PasswordResetRequest: {
      /** Email */
      email: string
    }
    /** PaymentMethod */
    PaymentMethod: {
      /**
       * Active
       * @default true
       */
      active: boolean
      /** Code */
      code: string
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'cash'
        | 'qris_static'
        | 'bank_transfer'
        | 'card_terminal'
        | 'ewallet'
        | 'platform_settlement'
        | 'voucher'
        | 'house_account'
      /** Name */
      name: string
    }
    /** PaymentMethodSettings */
    PaymentMethodSettings: {
      /** Methods */
      methods?: components['schemas']['PaymentMethod'][]
    }
    /** PostedDocument */
    PostedDocument: {
      /**
       * Doc Id
       * Format: uuid
       */
      doc_id: string
      /** Doc Type */
      doc_type: string
      /** Movements */
      movements: number
    }
    /** PriceIn */
    PriceIn: {
      /**
       * Channel Id
       * Format: uuid
       */
      channel_id: string
      /** Price */
      price: number
      /**
       * Valid From
       * Format: date
       */
      valid_from: string
    }
    /** PriceOut */
    PriceOut: {
      /**
       * Channel Id
       * Format: uuid
       */
      channel_id: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Price */
      price: number
      /**
       * Valid From
       * Format: date
       */
      valid_from: string
    }
    /** QtyLine */
    QtyLine: {
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Qty */
      qty: number | string
      /**
       * Unit Id
       * Format: uuid
       */
      unit_id: string
    }
    /** RecoveryCodesOut */
    RecoveryCodesOut: {
      /** Recovery Codes */
      recovery_codes: string[]
    }
    /** RoleOut */
    RoleOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Template Key */
      template_key: string | null
    }
    /** ServiceChargeSettings */
    ServiceChargeSettings: {
      /**
       * Before Tax
       * @default true
       */
      before_tax: boolean
      /** Channels */
      channels?: string[]
      /**
       * Enabled
       * @default false
       */
      enabled: boolean
      /**
       * Rate Bp
       * @default 0
       */
      rate_bp: number
    }
    /** SessionInfo */
    SessionInfo: {
      /** Active Tenant Id */
      active_tenant_id: string | null
      /** Csrf Token */
      csrf_token: string
      /** Mfa State */
      mfa_state: string
      /** Tenants */
      tenants: components['schemas']['TenantOption'][]
      user: components['schemas']['UserOut']
    }
    /** SessionOut */
    SessionOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Current */
      current: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Ip */
      ip: string | null
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string
      /** User Agent */
      user_agent: string | null
    }
    /**
     * SessionSettings
     * @description FR-IDN-009: tenant idle timeout within the platform limit.
     */
    SessionSettings: {
      /**
       * Idle Minutes
       * @default 60
       */
      idle_minutes: number
    }
    /** StockDocument */
    StockDocument: {
      /**
       * Blind
       * @default false
       */
      blind: boolean
      /**
       * Business Date
       * Format: date
       */
      business_date: string
      /** Count Type */
      count_type?: string | null
      /** Created By */
      created_by: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'waste' | 'adjustment' | 'count'
      /** Lines */
      lines?: components['schemas']['DocLine'][]
      /** Note */
      note: string | null
      /** Number */
      number: string
      /**
       * Outlet Id
       * Format: uuid
       */
      outlet_id: string
      /** Reason Code */
      reason_code?: string | null
      /** Status */
      status: string
    }
    /** StockRow */
    StockRow: {
      /** Avg Cost */
      avg_cost: string | null
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Name */
      name: string
      /** Qty */
      qty: string
      /** Sku */
      sku: string
      /** Unit Code */
      unit_code: string
      /** Value */
      value: number | null
    }
    /** StockSettings */
    StockSettings: {
      negative_stock?: components['schemas']['NegativeStockPolicy']
    }
    /** SubscriptionBanner */
    SubscriptionBanner: {
      /** Days Left */
      days_left: number | null
      /** State */
      state: string
    }
    /** SwitchTenantRequest */
    SwitchTenantRequest: {
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string
    }
    /** TaxRule */
    TaxRule: {
      /**
       * Active
       * @default true
       */
      active: boolean
      /**
       * Applies To Service Charge
       * @default true
       */
      applies_to_service_charge: boolean
      /** Id */
      id: string
      /** Name */
      name: string
      /**
       * Order
       * @default 0
       */
      order: number
      /** Outlet Ids */
      outlet_ids?: string[] | null
      /**
       * Price Includes Tax
       * @default false
       */
      price_includes_tax: boolean
      /** Rate Bp */
      rate_bp: number
    }
    /** TaxSettings */
    TaxSettings: {
      /** Rules */
      rules?: components['schemas']['TaxRule'][]
    }
    /** TenantOption */
    TenantOption: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
    }
    /** TranslationIn */
    TranslationIn: {
      /** Description */
      description?: string | null
      /** Language */
      language: string
      /** Name */
      name: string
    }
    /** TranslationOut */
    TranslationOut: {
      /** Description */
      description: string | null
      /** Language */
      language: string
      /** Name */
      name: string
    }
    /** UnitIn */
    UnitIn: {
      /** Code */
      code: string
      /**
       * Dimension
       * @enum {string}
       */
      dimension: 'mass' | 'volume' | 'count'
      /** Name */
      name: string
    }
    /** UnitOut */
    UnitOut: {
      /** Code */
      code: string
      /**
       * Dimension
       * @enum {string}
       */
      dimension: 'mass' | 'volume' | 'count'
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Platform */
      is_platform: boolean
      /** Name */
      name: string
    }
    /** UserOut */
    UserOut: {
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Locale */
      locale: string
      /** Name */
      name: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** ValuationRow */
    ValuationRow: {
      /**
       * Item Id
       * Format: uuid
       */
      item_id: string
      /** Name */
      name: string
      /** Qty */
      qty: string
      /** Sku */
      sku: string
      /** Unit Code */
      unit_code: string
      /** Value */
      value: number
    }
    /** WasteIn */
    WasteIn: {
      /**
       * Business Date
       * Format: date
       */
      business_date: string
      /**
       * Confirm Negative
       * @default false
       */
      confirm_negative: boolean
      /** Lines */
      lines: components['schemas']['QtyLine'][]
      /** Note */
      note?: string | null
      /**
       * Outlet Id
       * Format: uuid
       */
      outlet_id: string
      /**
       * Reason Code
       * @enum {string}
       */
      reason_code: 'spoilage' | 'expired' | 'preparation_loss' | 'damaged' | 'staff_meal' | 'other'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_alert_rules_api_v1_alert_rules_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRuleOut'][]
        }
      }
    }
  }
  create_alert_rule_api_v1_alert_rules_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AlertRuleIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRuleOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_alert_rule_api_v1_alert_rules__rule_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        rule_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_approval_rules_api_v1_approval_rules_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRuleOut'][]
        }
      }
    }
  }
  create_approval_rule_api_v1_approval_rules_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApprovalRuleIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRuleOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_approval_rule_api_v1_approval_rules__rule_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        rule_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  accept_invitation_api_v1_auth_invitations_accept_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationAccept']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  mfa_confirm_api_v1_auth_mfa_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CodeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryCodesOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  mfa_setup_api_v1_auth_mfa_setup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MfaSetupOut']
        }
      }
    }
  }
  mfa_verify_api_v1_auth_mfa_verify_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CodeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirm']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  request_password_reset_api_v1_auth_password_reset_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  current_session_api_v1_auth_session_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
    }
  }
  my_sessions_api_v1_auth_sessions_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOut'][]
        }
      }
    }
  }
  revoke_session_api_v1_auth_sessions__session_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  switch_tenant_api_v1_auth_switch_tenant_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SwitchTenantRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_bom_api_v1_catalog_boms__bom_id__get: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: never
      path: {
        bom_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BomOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_draft_api_v1_catalog_boms__bom_id__put: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: never
      path: {
        bom_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BomIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BomOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_draft_api_v1_catalog_boms__bom_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        bom_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  activate_api_v1_catalog_boms__bom_id__activate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        bom_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BomActivate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BomSummary']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_categories_api_v1_catalog_categories_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryOut'][]
        }
      }
    }
  }
  create_category_api_v1_catalog_categories_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_category_api_v1_catalog_categories__category_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        category_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_channels_api_v1_catalog_channels_get: {
    parameters: {
      query?: {
        include_inactive?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChannelOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_channel_api_v1_catalog_channels_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChannelIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChannelOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_channel_api_v1_catalog_channels__channel_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        channel_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChannelIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChannelOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_items_api_v1_catalog_items_get: {
    parameters: {
      query?: {
        lang?: string
        type?: ('ingredient' | 'semi_finished' | 'menu') | null
        category_id?: string | null
        q?: string | null
        include_inactive?: boolean
        limit?: number
        cursor?: string | null
        sort?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ItemSummary_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_item_api_v1_catalog_items_post: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: {
        'Idempotency-Key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ItemIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_item_api_v1_catalog_items__item_id__get: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_item_api_v1_catalog_items__item_id__put: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ItemUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_versions_api_v1_catalog_items__item_id__boms_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BomSummary'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_draft_api_v1_catalog_items__item_id__boms_post: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BomIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BomOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  item_costing_api_v1_catalog_items__item_id__costing_get: {
    parameters: {
      query?: {
        on?: string | null
        lang?: string
      }
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Costing']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  price_history_api_v1_catalog_items__item_id__prices_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_price_api_v1_catalog_items__item_id__prices_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PriceIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  effective_prices_api_v1_catalog_prices_get: {
    parameters: {
      query: {
        channel_id: string
        on?: string | null
        limit?: number
        cursor?: string | null
        sort?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_EffectivePrice_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_price_api_v1_catalog_prices__price_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        price_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_units_api_v1_catalog_units_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UnitOut'][]
        }
      }
    }
  }
  create_unit_api_v1_catalog_units_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UnitIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UnitOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_adjustment_api_v1_inventory_adjustments_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdjustmentIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_adjustment_api_v1_inventory_adjustments__doc_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdjustmentIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_adjustment_api_v1_inventory_adjustments__doc_id__submit_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  decide_adjustment_api_v1_inventory_adjustments__doc_id___decision__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
        decision: 'approve' | 'reject'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_count_api_v1_inventory_counts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CountIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  enter_counted_api_v1_inventory_counts__doc_id__lines_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CountedIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_count_api_v1_inventory_counts__doc_id__submit_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  decide_count_api_v1_inventory_counts__doc_id___decision__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
        decision: 'approve' | 'reject'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_documents_api_v1_inventory_documents__kind__get: {
    parameters: {
      query: {
        outlet_id: string
      }
      header?: never
      path: {
        kind: 'waste' | 'adjustments' | 'counts'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_document_api_v1_inventory_documents__kind___doc_id__get: {
    parameters: {
      query?: {
        lang?: string
      }
      header?: never
      path: {
        kind: 'waste' | 'adjustments' | 'counts'
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  movement_history_api_v1_inventory_movements_get: {
    parameters: {
      query: {
        outlet_id: string
        item_id?: string | null
        limit?: number
        cursor?: string | null
        sort?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_MovementOut_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  post_opening_api_v1_inventory_opening_post: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OpeningIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostedDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reverse_opening_api_v1_inventory_opening__doc_id__reverse_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostedDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stock_api_v1_inventory_stock_get: {
    parameters: {
      query: {
        outlet_id: string
        lang?: string
        limit?: number
        cursor?: string | null
        sort?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_StockRow_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  item_batches_api_v1_inventory_stock__item_id__batches_get: {
    parameters: {
      query: {
        outlet_id: string
      }
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stock_valuation_api_v1_inventory_valuation_get: {
    parameters: {
      query: {
        outlet_id: string
        on?: string | null
        lang?: string
        limit?: number
        cursor?: string | null
        sort?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ValuationRow_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  post_waste_api_v1_inventory_waste_post: {
    parameters: {
      query?: never
      header?: {
        'Idempotency-Key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WasteIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reverse_waste_api_v1_inventory_waste__doc_id__reverse_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StockDocument']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_invitation_api_v1_invitations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  capabilities_api_v1_me_capabilities_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Capabilities']
        }
      }
    }
  }
  list_outlets_api_v1_outlets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OutletOut'][]
        }
      }
    }
  }
  get_outlet_api_v1_outlets__outlet_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        outlet_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OutletOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_roles_api_v1_roles_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoleOut'][]
        }
      }
    }
  }
  all_settings_api_v1_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AllSettings']
        }
      }
    }
  }
  put_setting_api_v1_settings__key__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown
        }
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
