/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/alert-rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Alert Rules */
    get: operations['list_alert_rules_api_v1_alert_rules_get']
    put?: never
    /** Create Alert Rule */
    post: operations['create_alert_rule_api_v1_alert_rules_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/alert-rules/{rule_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Alert Rule */
    delete: operations['delete_alert_rule_api_v1_alert_rules__rule_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/approval-rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Approval Rules */
    get: operations['list_approval_rules_api_v1_approval_rules_get']
    put?: never
    /** Create Approval Rule */
    post: operations['create_approval_rule_api_v1_approval_rules_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/approval-rules/{rule_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Approval Rule */
    delete: operations['delete_approval_rule_api_v1_approval_rules__rule_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/invitations/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Accept Invitation
     * @description New email: creates the account with the given password. Existing account: the
     *     password must match it (proves the invitee owns that account). Then sign in normally.
     */
    post: operations['accept_invitation_api_v1_auth_invitations_accept_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mfa Confirm
     * @description Finish enrolment with a first code from the app; returns recovery codes once.
     */
    post: operations['mfa_confirm_api_v1_auth_mfa_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mfa Setup
     * @description Start (or restart) enrolment. Allowed when fully signed in or when enrolment is
     *     required; not while a code is still owed for an existing setup.
     */
    post: operations['mfa_setup_api_v1_auth_mfa_setup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mfa Verify
     * @description Second sign-in step: a TOTP code, or a one-time recovery code.
     */
    post: operations['mfa_verify_api_v1_auth_mfa_verify_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password-reset/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm Password Reset
     * @description Single use; sets the new password and signs the user out everywhere. 2FA still
     *     applies at the next sign-in, so a stolen mailbox alone cannot take over an owner.
     */
    post: operations['confirm_password_reset_api_v1_auth_password_reset_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password-reset/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request Password Reset
     * @description Always 202, whether or not the email has an account (no account enumeration).
     */
    post: operations['request_password_reset_api_v1_auth_password_reset_request_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current Session */
    get: operations['current_session_api_v1_auth_session_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * My Sessions
     * @description FR-IDN-007: the user's active sessions, newest activity first.
     */
    get: operations['my_sessions_api_v1_auth_sessions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/sessions/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Revoke Session
     * @description FR-IDN-007: revoke one of your own sessions (404 for anyone else's).
     */
    delete: operations['revoke_session_api_v1_auth_sessions__session_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/switch-tenant': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Switch Tenant
     * @description FR-IDN-005. The requested tenant is only a choice: it is checked against the user's
     *     memberships. The session is rotated (new token and CSRF token) because the privileges
     *     change, which defeats session fixation.
     */
    post: operations['switch_tenant_api_v1_auth_switch_tenant_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invitations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Invitation
     * @description FR-IDN-006: invite a person by email (single use, expiring link).
     */
    post: operations['create_invitation_api_v1_invitations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/capabilities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Capabilities
     * @description What the UI may show. Convenience only: every route re-checks on the server.
     */
    get: operations['capabilities_api_v1_me_capabilities_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/outlets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Outlets */
    get: operations['list_outlets_api_v1_outlets_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/outlets/{outlet_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Outlet
     * @description Another tenant's outlet is invisible (RLS); one outside the caller's scope is 404 too.
     */
    get: operations['get_outlet_api_v1_outlets__outlet_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/roles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Roles
     * @description The tenant's own roles (templates with tenant_id NULL are excluded).
     */
    get: operations['list_roles_api_v1_roles_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** All Settings */
    get: operations['all_settings_api_v1_settings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Setting */
    put: operations['put_setting_api_v1_settings__key__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness plus database status (NFR-010). 503 lets uptime checks and Docker see an outage.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AlertRuleIn */
    AlertRuleIn: {
      /**
       * Alert Type
       * @enum {string}
       */
      alert_type:
        | 'below_reorder_point'
        | 'low_days_of_inventory'
        | 'batch_near_expiry'
        | 'expired_stock'
        | 'negative_stock'
        | 'count_variance'
        | 'food_cost_above_target'
        | 'approval_requested'
      /**
       * Channel
       * @default in_app
       * @enum {string}
       */
      channel: 'in_app' | 'email'
      /** Recipient Role Id */
      recipient_role_id?: string | null
      /** Recipient User Id */
      recipient_user_id?: string | null
    }
    /** AlertRuleOut */
    AlertRuleOut: {
      /**
       * Alert Type
       * @enum {string}
       */
      alert_type:
        | 'below_reorder_point'
        | 'low_days_of_inventory'
        | 'batch_near_expiry'
        | 'expired_stock'
        | 'negative_stock'
        | 'count_variance'
        | 'food_cost_above_target'
        | 'approval_requested'
      /**
       * Channel
       * @default in_app
       * @enum {string}
       */
      channel: 'in_app' | 'email'
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Recipient Role Id */
      recipient_role_id?: string | null
      /** Recipient User Id */
      recipient_user_id?: string | null
    }
    /**
     * AllSettings
     * @description Response of GET /settings, typed so the generated frontend client knows every field.
     */
    AllSettings: {
      numbering: components['schemas']['NumberingSettings']
      payment_methods: components['schemas']['PaymentMethodSettings']
      service_charge: components['schemas']['ServiceChargeSettings']
      session: components['schemas']['SessionSettings']
      tax: components['schemas']['TaxSettings']
    }
    /** ApprovalRuleIn */
    ApprovalRuleIn: {
      /**
       * Approver Role Id
       * Format: uuid
       */
      approver_role_id: string
      /**
       * Document Type
       * @enum {string}
       */
      document_type:
        | 'purchase_order'
        | 'transfer'
        | 'adjustment'
        | 'count'
        | 'void'
        | 'refund'
        | 'discount'
        | 'journal'
      /** Min Amount */
      min_amount: number
      /** Outlet Id */
      outlet_id?: string | null
    }
    /** ApprovalRuleOut */
    ApprovalRuleOut: {
      /**
       * Approver Role Id
       * Format: uuid
       */
      approver_role_id: string
      /**
       * Document Type
       * @enum {string}
       */
      document_type:
        | 'purchase_order'
        | 'transfer'
        | 'adjustment'
        | 'count'
        | 'void'
        | 'refund'
        | 'discount'
        | 'journal'
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Min Amount */
      min_amount: number
      /** Outlet Id */
      outlet_id?: string | null
    }
    /** Capabilities */
    Capabilities: {
      /** All Outlets */
      all_outlets: boolean
      /** Modules */
      modules: string[]
      /** Nav */
      nav: string[]
      /** Outlet Ids */
      outlet_ids: string[]
      /** Permissions */
      permissions: string[]
      subscription: components['schemas']['SubscriptionBanner']
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string
    }
    /** CodeRequest */
    CodeRequest: {
      /** Code */
      code: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** InvitationAccept */
    InvitationAccept: {
      /** Name */
      name?: string | null
      /** Password */
      password: string
      /** Token */
      token: string
    }
    /** InvitationCreate */
    InvitationCreate: {
      /** Email */
      email: string
      /**
       * Role Id
       * Format: uuid
       */
      role_id: string
    }
    /** InvitationOut */
    InvitationOut: {
      /** Email */
      email: string
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** MfaSetupOut */
    MfaSetupOut: {
      /** Otpauth Uri */
      otpauth_uri: string
      /** Secret */
      secret: string
    }
    /** NumberingFormat */
    NumberingFormat: {
      /**
       * Padding
       * @default 5
       */
      padding: number
      /** Prefix */
      prefix: string
      /**
       * Reset
       * @default yearly
       * @enum {string}
       */
      reset: 'yearly' | 'never'
    }
    /**
     * NumberingSettings
     * @description FR-TEN-009: per document type; numbers are allocated per outlet and year.
     */
    NumberingSettings: {
      /** Formats */
      formats?: {
        [key: string]: components['schemas']['NumberingFormat']
      }
    }
    /** OutletOut */
    OutletOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Active */
      is_active: boolean
      /** Name */
      name: string
      /** Timezone */
      timezone: string
      /** Type */
      type: string
    }
    /** PasswordResetConfirm */
    PasswordResetConfirm: {
      /** New Password */
      new_password: string
      /** Token */
      token: string
    }
    /** PasswordResetRequest */
    PasswordResetRequest: {
      /** Email */
      email: string
    }
    /** PaymentMethod */
    PaymentMethod: {
      /**
       * Active
       * @default true
       */
      active: boolean
      /** Code */
      code: string
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'cash'
        | 'qris_static'
        | 'bank_transfer'
        | 'card_terminal'
        | 'ewallet'
        | 'platform_settlement'
        | 'voucher'
        | 'house_account'
      /** Name */
      name: string
    }
    /** PaymentMethodSettings */
    PaymentMethodSettings: {
      /** Methods */
      methods?: components['schemas']['PaymentMethod'][]
    }
    /** RecoveryCodesOut */
    RecoveryCodesOut: {
      /** Recovery Codes */
      recovery_codes: string[]
    }
    /** RoleOut */
    RoleOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Template Key */
      template_key: string | null
    }
    /** ServiceChargeSettings */
    ServiceChargeSettings: {
      /**
       * Before Tax
       * @default true
       */
      before_tax: boolean
      /** Channels */
      channels?: string[]
      /**
       * Enabled
       * @default false
       */
      enabled: boolean
      /**
       * Rate Bp
       * @default 0
       */
      rate_bp: number
    }
    /** SessionInfo */
    SessionInfo: {
      /** Active Tenant Id */
      active_tenant_id: string | null
      /** Csrf Token */
      csrf_token: string
      /** Mfa State */
      mfa_state: string
      /** Tenants */
      tenants: components['schemas']['TenantOption'][]
      user: components['schemas']['UserOut']
    }
    /** SessionOut */
    SessionOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Current */
      current: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Ip */
      ip: string | null
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string
      /** User Agent */
      user_agent: string | null
    }
    /**
     * SessionSettings
     * @description FR-IDN-009: tenant idle timeout within the platform limit.
     */
    SessionSettings: {
      /**
       * Idle Minutes
       * @default 60
       */
      idle_minutes: number
    }
    /** SubscriptionBanner */
    SubscriptionBanner: {
      /** Days Left */
      days_left: number | null
      /** State */
      state: string
    }
    /** SwitchTenantRequest */
    SwitchTenantRequest: {
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string
    }
    /** TaxRule */
    TaxRule: {
      /**
       * Active
       * @default true
       */
      active: boolean
      /**
       * Applies To Service Charge
       * @default true
       */
      applies_to_service_charge: boolean
      /** Id */
      id: string
      /** Name */
      name: string
      /**
       * Order
       * @default 0
       */
      order: number
      /** Outlet Ids */
      outlet_ids?: string[] | null
      /**
       * Price Includes Tax
       * @default false
       */
      price_includes_tax: boolean
      /** Rate Bp */
      rate_bp: number
    }
    /** TaxSettings */
    TaxSettings: {
      /** Rules */
      rules?: components['schemas']['TaxRule'][]
    }
    /** TenantOption */
    TenantOption: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
    }
    /** UserOut */
    UserOut: {
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Locale */
      locale: string
      /** Name */
      name: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_alert_rules_api_v1_alert_rules_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRuleOut'][]
        }
      }
    }
  }
  create_alert_rule_api_v1_alert_rules_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AlertRuleIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRuleOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_alert_rule_api_v1_alert_rules__rule_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        rule_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_approval_rules_api_v1_approval_rules_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRuleOut'][]
        }
      }
    }
  }
  create_approval_rule_api_v1_approval_rules_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApprovalRuleIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRuleOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_approval_rule_api_v1_approval_rules__rule_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        rule_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  accept_invitation_api_v1_auth_invitations_accept_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationAccept']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  mfa_confirm_api_v1_auth_mfa_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CodeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryCodesOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  mfa_setup_api_v1_auth_mfa_setup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MfaSetupOut']
        }
      }
    }
  }
  mfa_verify_api_v1_auth_mfa_verify_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CodeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirm']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  request_password_reset_api_v1_auth_password_reset_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  current_session_api_v1_auth_session_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
    }
  }
  my_sessions_api_v1_auth_sessions_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOut'][]
        }
      }
    }
  }
  revoke_session_api_v1_auth_sessions__session_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  switch_tenant_api_v1_auth_switch_tenant_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SwitchTenantRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_invitation_api_v1_invitations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  capabilities_api_v1_me_capabilities_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Capabilities']
        }
      }
    }
  }
  list_outlets_api_v1_outlets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OutletOut'][]
        }
      }
    }
  }
  get_outlet_api_v1_outlets__outlet_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        outlet_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OutletOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_roles_api_v1_roles_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoleOut'][]
        }
      }
    }
  }
  all_settings_api_v1_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AllSettings']
        }
      }
    }
  }
  put_setting_api_v1_settings__key__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown
        }
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
