"""CLAUDE.md rule 11: migrations upgrade from empty, downgrade fully, re-upgrade, and match
the SQLAlchemy models (no drift)."""

from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from tests.conftest import alembic_config, migrate_fresh


def test_upgrade_downgrade_upgrade_and_no_model_drift() -> None:
    config = alembic_config(migrate_fresh("pos_test_migrations"))
    command.downgrade(config, "base")
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - message is the useful part
        raise AssertionError(f"models and migrations differ: {exc}") from None
