"""sessions and sign-in throttle

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 06:41:11.745308
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import APP_ROLE, AUTH_ROLE, grant

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_throttle",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_auth_throttle")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("active_tenant_id", sa.Uuid(), nullable=True),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["active_tenant_id"], ["tenants.id"], name=op.f("fk_sessions_active_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_sessions_user_id_revoked_at"), "sessions", ["user_id", "revoked_at"], unique=False
    )

    # Global identity tables: no RLS (not tenant-owned); only the identity service uses them.
    grant("sessions", "SELECT, INSERT, UPDATE")  # revocation sets revoked_at, never deletes
    grant("auth_throttle", "SELECT, INSERT, UPDATE, DELETE")

    # Narrow cross-tenant read for sign-in and tenant switching (FR-IDN-005). Runs as
    # pos_auth (BYPASSRLS) but can only return the memberships of the user it is asked about.
    op.execute(
        f"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{AUTH_ROLE}') "
        f"THEN CREATE ROLE {AUTH_ROLE} NOLOGIN BYPASSRLS; END IF; END $$"
    )
    op.execute(f"GRANT USAGE ON SCHEMA public TO {AUTH_ROLE}")
    op.execute(f"GRANT SELECT ON memberships, tenants TO {AUTH_ROLE}")
    op.execute("""
        CREATE FUNCTION auth_user_memberships(p_user_id uuid)
        RETURNS TABLE (tenant_id uuid, tenant_name text, tenant_status text,
                       membership_id uuid, role_id uuid, scope text, status text)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
            SELECT m.tenant_id, t.name, t.status, m.id, m.role_id, m.scope, m.status
            FROM memberships m JOIN tenants t ON t.id = m.tenant_id
            WHERE m.user_id = p_user_id
            ORDER BY t.name
        $$
    """)
    op.execute(f"ALTER FUNCTION auth_user_memberships(uuid) OWNER TO {AUTH_ROLE}")
    op.execute("REVOKE ALL ON FUNCTION auth_user_memberships(uuid) FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION auth_user_memberships(uuid) TO {APP_ROLE}")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS auth_user_memberships(uuid)")
    op.drop_index(op.f("ix_sessions_user_id_revoked_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("auth_throttle")
