"""two-factor, invitations and password reset

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 06:52:15.043673
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import APP_ROLE, AUTH_ROLE, enable_tenant_rls, grant

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_resets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_resets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_resets")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_resets_token_hash")),
    )
    op.create_index(
        op.f("ix_password_resets_user_id"), "password_resets", ["user_id"], unique=False
    )
    op.create_table(
        "recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.LargeBinary(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recovery_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_recovery_codes_code_hash")),
    )
    op.create_index(op.f("ix_recovery_codes_user_id"), "recovery_codes", ["user_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_invitations_invited_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["roles.tenant_id", "roles.id"],
            name=op.f("fk_invitations_tenant_id_role_id_roles"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_invitations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        op.f("ix_invitations_tenant_id_email"), "invitations", ["tenant_id", "email"], unique=False
    )
    op.add_column(
        "roles", sa.Column("requires_mfa", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "sessions", sa.Column("mfa_state", sa.Text(), server_default="ok", nullable=False)
    )
    op.add_column("users", sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("totp_last_step", sa.BigInteger(), nullable=True))
    op.create_check_constraint(
        "mfa_state_valid", "sessions", "mfa_state IN ('ok', 'verify', 'enroll')"
    )

    grant("recovery_codes", "SELECT, INSERT, UPDATE, DELETE")
    grant("password_resets", "SELECT, INSERT, UPDATE")
    grant("invitations", "SELECT, INSERT, UPDATE")
    enable_tenant_rls("invitations")

    # Cross-tenant reads needed before a tenant is chosen, owned by pos_auth (see 0002).
    op.execute(f"GRANT SELECT ON invitations, roles TO {AUTH_ROLE}")
    op.execute("""
        CREATE FUNCTION auth_invitation_by_token(p_token_hash bytea)
        RETURNS TABLE (id uuid, tenant_id uuid, email text, role_id uuid,
                       expires_at timestamptz, used_at timestamptz)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
            SELECT i.id, i.tenant_id, i.email::text, i.role_id, i.expires_at, i.used_at
            FROM invitations i WHERE i.token_hash = p_token_hash
        $$
    """)
    op.execute("""
        CREATE FUNCTION auth_user_requires_mfa(p_user_id uuid) RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
            SELECT EXISTS (
                SELECT 1 FROM memberships m
                JOIN roles r ON r.id = m.role_id
                JOIN tenants t ON t.id = m.tenant_id
                WHERE m.user_id = p_user_id AND m.status = 'active'
                  AND t.status = 'active' AND r.requires_mfa
            )
        $$
    """)
    for fn in ("auth_invitation_by_token(bytea)", "auth_user_requires_mfa(uuid)"):
        op.execute(f"ALTER FUNCTION {fn} OWNER TO {AUTH_ROLE}")
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")
        op.execute(f"GRANT EXECUTE ON FUNCTION {fn} TO {APP_ROLE}")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS auth_invitation_by_token(bytea)")
    op.execute("DROP FUNCTION IF EXISTS auth_user_requires_mfa(uuid)")
    op.drop_constraint(op.f("ck_sessions_mfa_state_valid"), "sessions")
    op.drop_column("users", "totp_last_step")
    op.drop_column("users", "totp_enabled_at")
    op.drop_column("sessions", "mfa_state")
    op.drop_column("roles", "requires_mfa")
    op.drop_index(op.f("ix_invitations_tenant_id_email"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_recovery_codes_user_id"), table_name="recovery_codes")
    op.drop_table("recovery_codes")
    op.drop_index(op.f("ix_password_resets_user_id"), table_name="password_resets")
    op.drop_table("password_resets")
