"""modules, subscriptions and role templates

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 07:23:26.235713
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("plan_type", sa.Text(), server_default="free", nullable=False),
        sa.Column(
            "starts_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("reminders_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "reminder_days",
            postgresql.ARRAY(sa.Integer()),
            server_default="{14,7,3,1}",
            nullable=False,
        ),
        sa.Column("suspended", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "plan_type IN ('free', 'paid')", name=op.f("ck_subscriptions_plan_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_subscriptions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_subscriptions")),
    )
    op.create_table(
        "tenant_modules",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "enabled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tenant_modules_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "module", name=op.f("pk_tenant_modules")),
    )
    op.add_column("roles", sa.Column("template_key", sa.String(length=40), nullable=True))

    # Subscription dates are written by the platform admin path (slice 0.6), not tenants.
    grant("subscriptions", "SELECT")
    grant("tenant_modules", "SELECT, INSERT, UPDATE")  # owners switch modules (FR-TEN-003)
    for table in ("subscriptions", "tenant_modules"):
        enable_tenant_rls(table)


def downgrade() -> None:
    op.drop_column("roles", "template_key")
    op.drop_table("tenant_modules")
    op.drop_table("subscriptions")
