"""platform admin

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-07 08:20:24.814820
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import admin_access, enable_tenant_rls, ensure_admin_role

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("totp_last_step", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('super_admin', 'support')", name=op.f("ck_admin_users_role_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name=op.f("ck_admin_users_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("email", name=op.f("uq_admin_users_email")),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("mfa_state", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.CheckConstraint(
            "mfa_state IN ('ok', 'verify', 'enroll')",
            name=op.f("ck_admin_sessions_mfa_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin_users.id"], name=op.f("fk_admin_sessions_admin_id_admin_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_admin_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_admin_sessions_admin_id_revoked_at"),
        "admin_sessions",
        ["admin_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "impersonation_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_users.id"],
            name=op.f("fk_impersonation_sessions_admin_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_impersonation_sessions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_impersonation_sessions")),
    )
    op.create_index(
        op.f("ix_impersonation_sessions_tenant_id_started_at"),
        "impersonation_sessions",
        ["tenant_id", "started_at"],
        unique=False,
    )
    op.add_column("subscriptions", sa.Column("last_state", sa.Text(), nullable=True))

    op.alter_column("invitations", "invited_by", nullable=True)  # platform-sent invitations

    ensure_admin_role()
    # Platform tables: admin role only (the tenant API role gets nothing).
    for table in ("admin_users", "admin_sessions"):
        admin_access(table, "SELECT, INSERT, UPDATE", rls=False)
    enable_tenant_rls("impersonation_sessions")  # has tenant_id, so RLS like every tenant table
    admin_access("impersonation_sessions", "SELECT, INSERT, UPDATE")
    # Tenant tables the console manages (FR-ADM-001, FR-SUB-001/005).
    for table in ("tenants", "subscriptions", "tenant_modules", "roles", "role_permissions"):
        admin_access(table, "SELECT, INSERT, UPDATE")
    admin_access("invitations", "SELECT, INSERT")  # the new tenant's owner invitation
    admin_access("memberships", "SELECT")
    admin_access("outlets", "SELECT")
    admin_access("audit_log", "SELECT, INSERT")  # admin actions are visible to the owner
    admin_access("users", "SELECT", rls=False)
    admin_access("auth_throttle", "SELECT, INSERT, UPDATE, DELETE", rls=False)


def downgrade() -> None:
    op.execute("DELETE FROM invitations WHERE invited_by IS NULL")
    op.alter_column("invitations", "invited_by", nullable=False)
    for table in (
        "tenants",
        "subscriptions",
        "tenant_modules",
        "roles",
        "role_permissions",
        "invitations",
        "memberships",
        "outlets",
        "audit_log",
    ):
        op.execute(f"DROP POLICY IF EXISTS platform_admin ON {table}")
    op.drop_column("subscriptions", "last_state")
    op.drop_index(
        op.f("ix_impersonation_sessions_tenant_id_started_at"), table_name="impersonation_sessions"
    )
    op.drop_table("impersonation_sessions")
    op.drop_index(op.f("ix_admin_sessions_admin_id_revoked_at"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_table("admin_users")
