"""catalog: units, categories, items, translations, conversions (slice 1b)

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-07 13:29:18.317774
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_id"],
            ["item_categories.tenant_id", "item_categories.id"],
            name=op.f("fk_item_categories_tenant_id_parent_id_item_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_item_categories_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_item_categories_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "parent_id",
            "name",
            name=op.f("uq_item_categories_tenant_id_parent_id_name"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "dimension IN ('mass', 'volume', 'count')", name=op.f("ck_units_dimension_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_units_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint(
            "tenant_id",
            "code",
            name=op.f("uq_units_tenant_id_code"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("base_unit_id", sa.Uuid(), nullable=False),
        sa.Column("is_stocked", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("storage_type", sa.Text(), nullable=True),
        sa.Column(
            "allergens", postgresql.ARRAY(sa.String(length=40)), server_default="{}", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "storage_type IS NULL OR storage_type IN ('frozen', 'chilled', 'dry')",
            name=op.f("ck_items_storage_type_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('ingredient', 'semi_finished', 'menu')", name=op.f("ck_items_type_valid")
        ),
        sa.CheckConstraint(
            "shelf_life_days IS NULL OR shelf_life_days > 0", name=op.f("ck_items_shelf_life")
        ),
        sa.ForeignKeyConstraint(
            ["base_unit_id"], ["units.id"], name=op.f("fk_items_base_unit_id_units")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["item_categories.tenant_id", "item_categories.id"],
            name=op.f("fk_items_tenant_id_category_id_item_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_items_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_items_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "sku", name=op.f("uq_items_tenant_id_sku")),
    )
    op.create_index(
        op.f("ix_items_tenant_id_type_is_active"),
        "items",
        ["tenant_id", "type", "is_active"],
        unique=False,
    )
    op.create_table(
        "item_translations",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_item_translations_tenant_id_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_item_translations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("item_id", "language", name=op.f("pk_item_translations")),
    )
    op.create_index(
        op.f("ix_item_translations_tenant_id_language_name"),
        "item_translations",
        ["tenant_id", "language", "name"],
        unique=False,
    )
    op.create_table(
        "item_unit_conversions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("factor_to_base", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.CheckConstraint(
            "factor_to_base > 0", name=op.f("ck_item_unit_conversions_factor_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_item_unit_conversions_tenant_id_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_item_unit_conversions_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_item_unit_conversions_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("item_id", "unit_id", name=op.f("pk_item_unit_conversions")),
    )
    op.create_index(
        op.f("ix_item_unit_conversions_tenant_id_item_id"),
        "item_unit_conversions",
        ["tenant_id", "item_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Platform units (tenant_id NULL), inserted before RLS so the owner may write them.
    op.execute(
        "INSERT INTO units (id, tenant_id, code, name, dimension) VALUES "
        "(gen_random_uuid(), NULL, 'g', 'gram', 'mass'), "
        "(gen_random_uuid(), NULL, 'kg', 'kilogram', 'mass'), "
        "(gen_random_uuid(), NULL, 'ml', 'millilitre', 'volume'), "
        "(gen_random_uuid(), NULL, 'l', 'litre', 'volume'), "
        "(gen_random_uuid(), NULL, 'pcs', 'piece', 'count')"
    )
    # Units: no UPDATE/DELETE, so a tenant can never touch the shared platform rows.
    grant("units", "SELECT, INSERT")
    grant("item_categories", "SELECT, INSERT, UPDATE")  # archived via is_active, never deleted
    grant("items", "SELECT, INSERT, UPDATE")
    grant("item_translations", "SELECT, INSERT, DELETE")  # replaced as a set on save
    grant("item_unit_conversions", "SELECT, INSERT, DELETE")
    enable_tenant_rls("units", readable_templates=True)
    for table in ("item_categories", "items", "item_translations", "item_unit_conversions"):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_item_unit_conversions_tenant_id_item_id"), table_name="item_unit_conversions"
    )
    op.drop_table("item_unit_conversions")
    op.drop_index(
        op.f("ix_item_translations_tenant_id_language_name"), table_name="item_translations"
    )
    op.drop_table("item_translations")
    op.drop_index(op.f("ix_items_tenant_id_type_is_active"), table_name="items")
    op.drop_table("items")
    op.drop_table("units")
    op.drop_table("item_categories")
    # ### end Alembic commands ###
