"""uploads and item photos

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-07 18:51:46.199348
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=120), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('item_photo', 'background', 'waste_photo', 'invoice')",
            name=op.f("ck_uploads_purpose_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_uploads_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_uploads_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "purpose", "sha256", name=op.f("uq_uploads_tenant_id_purpose_sha256")
        ),
    )
    op.create_index(
        op.f("ix_uploads_tenant_id_created_at"),
        "uploads",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.add_column("items", sa.Column("photo_upload_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_items_tenant_id_photo_upload_id_uploads"),
        "items",
        "uploads",
        ["tenant_id", "photo_upload_id"],
        ["tenant_id", "id"],
    )
    # ### end Alembic commands ###
    grant("uploads", "SELECT, INSERT")  # files are immutable; replaced, never edited
    enable_tenant_rls("uploads")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_items_tenant_id_photo_upload_id_uploads"), "items", type_="foreignkey"
    )
    op.drop_column("items", "photo_upload_id")
    op.drop_index(op.f("ix_uploads_tenant_id_created_at"), table_name="uploads")
    op.drop_table("uploads")
    # ### end Alembic commands ###
