"""ai image usage

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-08 03:52:55.835715
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage_daily",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("neurons", sa.Integer(), server_default="0", nullable=False),
        sa.Column("images", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_ai_usage_daily")),
    )
    op.create_table(
        "ai_image_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.String(length=300), nullable=False),
        sa.Column("neurons", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_ai_image_requests_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_image_requests")),
    )
    op.create_index(
        op.f("ix_ai_image_requests_tenant_id_created_at"),
        "ai_image_requests",
        ["tenant_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    # Platform-wide counter: only a date and numbers, no tenant data, so no RLS.
    grant("ai_usage_daily", "SELECT, INSERT, UPDATE")
    grant("ai_image_requests", "SELECT, INSERT, UPDATE")
    enable_tenant_rls("ai_image_requests")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_image_requests_tenant_id_created_at"), table_name="ai_image_requests")
    op.drop_table("ai_image_requests")
    op.drop_table("ai_usage_daily")
    # ### end Alembic commands ###
