"""import batches

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-08 10:45:17.529457
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.Text(), server_default="committed", nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reverted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('items', 'recipes', 'vendors', 'opening_stock')",
            name=op.f("ck_import_batches_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('committed', 'reverted')", name=op.f("ck_import_batches_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_import_batches_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint(
            "tenant_id",
            "kind",
            "file_sha256",
            name=op.f("uq_import_batches_tenant_id_kind_file_sha256"),
        ),
    )
    # ### end Alembic commands ###
    grant("import_batches", "SELECT, INSERT, UPDATE")  # status changes on revert
    enable_tenant_rls("import_batches")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("import_batches")
    # ### end Alembic commands ###
