"""item tracking mode and standard cost

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-08 11:18:42.409563
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("tracking_mode", sa.Text(), server_default="exact", nullable=False)
    )
    op.add_column(
        "items", sa.Column("standard_cost", sa.Numeric(precision=18, scale=6), nullable=True)
    )
    # Existing non-stocked items become "untracked" so the new rule holds for old rows.
    op.execute("UPDATE items SET tracking_mode = 'untracked' WHERE NOT is_stocked")
    op.create_check_constraint(
        "tracking_mode_valid", "items", "tracking_mode IN ('exact', 'estimated', 'untracked')"
    )
    op.create_check_constraint(
        "tracking_matches_stocked", "items", "(tracking_mode = 'untracked') = (NOT is_stocked)"
    )
    op.create_check_constraint(
        "standard_cost", "items", "standard_cost IS NULL OR standard_cost >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_items_standard_cost"), "items", type_="check")
    op.drop_constraint(op.f("ck_items_tracking_matches_stocked"), "items", type_="check")
    op.drop_constraint(op.f("ck_items_tracking_mode_valid"), "items", type_="check")
    op.drop_column("items", "standard_cost")
    op.drop_column("items", "tracking_mode")
    # ### end Alembic commands ###
