"""purchasing vendors receipts

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-08 11:38:50.632521
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_name", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("tax_id", sa.String(length=40), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lead_time_days", sa.Integer(), server_default="1", nullable=False),
        sa.Column("bank_details_enc", sa.LargeBinary(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lead_time_days >= 0", name=op.f("ck_vendors_lead_time")),
        sa.CheckConstraint("payment_terms_days >= 0", name=op.f("ck_vendors_terms")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendors_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendors_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_vendors_tenant_id_name")),
    )
    op.create_table(
        "goods_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("vendor_name", sa.String(length=200), nullable=True),
        sa.Column("po_id", sa.Uuid(), nullable=True),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default="posted", nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("invoice_upload_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('posted', 'reversed')", name=op.f("ck_goods_receipts_status_valid")
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_goods_receipts_total")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "invoice_upload_id"],
            ["uploads.tenant_id", "uploads.id"],
            name=op.f("fk_goods_receipts_tenant_id_invoice_upload_id_uploads"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_goods_receipts_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "vendor_id"],
            ["vendors.tenant_id", "vendors.id"],
            name=op.f("fk_goods_receipts_tenant_id_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_goods_receipts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipts")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_goods_receipts_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_goods_receipts_tenant_id_outlet_id_business_date"),
        "goods_receipts",
        ["tenant_id", "outlet_id", "business_date"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("line_total", sa.BigInteger(), nullable=False),
        sa.Column("lot_code", sa.String(length=64), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.CheckConstraint("line_total >= 0", name=op.f("ck_goods_receipt_lines_line_total")),
        sa.CheckConstraint("qty > 0", name=op.f("ck_goods_receipt_lines_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_goods_receipt_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receipt_id"],
            ["goods_receipts.tenant_id", "goods_receipts.id"],
            name=op.f("fk_goods_receipt_lines_tenant_id_receipt_id_goods_receipts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_goods_receipt_lines_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_goods_receipt_lines_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_goods_receipt_lines_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_tenant_id_receipt_id"),
        "goods_receipt_lines",
        ["tenant_id", "receipt_id"],
        unique=False,
    )
    op.create_table(
        "vendor_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_sku", sa.String(length=64), nullable=True),
        sa.Column("pack_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("pack_unit_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("min_order_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.CheckConstraint("pack_qty > 0", name=op.f("ck_vendor_items_pack_qty")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_vendor_items_price")),
        sa.ForeignKeyConstraint(
            ["pack_unit_id"], ["units.id"], name=op.f("fk_vendor_items_pack_unit_id_units")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_vendor_items_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "vendor_id"],
            ["vendors.tenant_id", "vendors.id"],
            name=op.f("fk_vendor_items_tenant_id_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_items_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendor_items_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "vendor_id",
            "item_id",
            "pack_unit_id",
            "valid_from",
            name=op.f("uq_vendor_items_tenant_id_vendor_id_item_id_pack_unit_id_valid_from"),
        ),
    )
    op.create_index(
        op.f("ix_vendor_items_tenant_id_item_id"),
        "vendor_items",
        ["tenant_id", "item_id"],
        unique=False,
    )
    op.create_table(
        "vendor_price_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.Column("source_doc_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_vendor_price_history_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_price_history_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_price_history")),
    )
    op.create_index(
        op.f("ix_vendor_price_history_tenant_id_item_id_observed_at"),
        "vendor_price_history",
        ["tenant_id", "item_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    grant("vendors", "SELECT, INSERT, UPDATE")  # archived with is_active, never deleted
    grant("vendor_items", "SELECT, INSERT")  # a new price is a new row (history kept)
    grant("goods_receipts", "SELECT, INSERT, UPDATE")  # status changes on reversal only
    grant("goods_receipt_lines", "SELECT, INSERT")
    grant("vendor_price_history", "SELECT, INSERT")
    make_append_only("vendor_price_history")
    for table in (
        "vendors",
        "vendor_items",
        "goods_receipts",
        "goods_receipt_lines",
        "vendor_price_history",
    ):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vendor_price_history_tenant_id_item_id_observed_at"),
        table_name="vendor_price_history",
    )
    op.drop_table("vendor_price_history")
    op.drop_index(op.f("ix_vendor_items_tenant_id_item_id"), table_name="vendor_items")
    op.drop_table("vendor_items")
    op.drop_index(
        op.f("ix_goods_receipt_lines_tenant_id_receipt_id"), table_name="goods_receipt_lines"
    )
    op.drop_table("goods_receipt_lines")
    op.drop_index(
        op.f("ix_goods_receipts_tenant_id_outlet_id_business_date"), table_name="goods_receipts"
    )
    op.drop_table("goods_receipts")
    op.drop_table("vendors")
    # ### end Alembic commands ###
