"""purchase orders

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-08 11:53:56.261152
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=True),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("total", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved', 'rejected', 'partially_received', 'received', 'cancelled')",
            name=op.f("ck_purchase_orders_status_valid"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_purchase_orders_total")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_purchase_orders_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "vendor_id"],
            ["vendors.tenant_id", "vendors.id"],
            name=op.f("fk_purchase_orders_tenant_id_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_purchase_orders_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchase_orders_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_purchase_orders_tenant_id_outlet_id_status"),
        "purchase_orders",
        ["tenant_id", "outlet_id", "status"],
        unique=False,
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column(
            "received_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_purchase_order_lines_qty")),
        sa.CheckConstraint("received_qty >= 0", name=op.f("ck_purchase_order_lines_received_qty")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_purchase_order_lines_unit_price")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_purchase_order_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "po_id"],
            ["purchase_orders.tenant_id", "purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_tenant_id_po_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_purchase_order_lines_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_purchase_order_lines_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchase_order_lines_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_tenant_id_po_id"),
        "purchase_order_lines",
        ["tenant_id", "po_id"],
        unique=False,
    )
    op.create_table(
        "vendor_lead_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("ordered_at", sa.Date(), nullable=False),
        sa.Column("received_at", sa.Date(), nullable=False),
        sa.Column("source_doc_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_vendor_lead_history_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "vendor_id"],
            ["vendors.tenant_id", "vendors.id"],
            name=op.f("fk_vendor_lead_history_tenant_id_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_lead_history_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_lead_history")),
    )
    op.create_index(
        op.f("ix_vendor_lead_history_tenant_id_vendor_id_item_id"),
        "vendor_lead_history",
        ["tenant_id", "vendor_id", "item_id"],
        unique=False,
    )
    op.add_column("goods_receipt_lines", sa.Column("po_line_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_goods_receipts_tenant_id_po_id_purchase_orders"),
        "goods_receipts",
        "purchase_orders",
        ["tenant_id", "po_id"],
        ["tenant_id", "id"],
    )
    # ### end Alembic commands ###
    grant("purchase_orders", "SELECT, INSERT, UPDATE")  # cancelled, never deleted
    grant("purchase_order_lines", "SELECT, INSERT, UPDATE, DELETE")  # editable while draft
    grant("vendor_lead_history", "SELECT, INSERT")
    make_append_only("vendor_lead_history")
    for table in ("purchase_orders", "purchase_order_lines", "vendor_lead_history"):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_goods_receipts_tenant_id_po_id_purchase_orders"),
        "goods_receipts",
        type_="foreignkey",
    )
    op.drop_column("goods_receipt_lines", "po_line_id")
    op.drop_index(
        op.f("ix_vendor_lead_history_tenant_id_vendor_id_item_id"), table_name="vendor_lead_history"
    )
    op.drop_table("vendor_lead_history")
    op.drop_index(
        op.f("ix_purchase_order_lines_tenant_id_po_id"), table_name="purchase_order_lines"
    )
    op.drop_table("purchase_order_lines")
    op.drop_index(
        op.f("ix_purchase_orders_tenant_id_outlet_id_status"), table_name="purchase_orders"
    )
    op.drop_table("purchase_orders")
    # ### end Alembic commands ###
