"""production orders

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-08 12:11:41.387740
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("bom_id", sa.Uuid(), nullable=True),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default="planned", nullable=False),
        sa.Column("planned_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("actual_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("input_value", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("lot_code", sa.String(length=60), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('planned', 'completed', 'cancelled', 'reversed')",
            name=op.f("ck_production_orders_status_valid"),
        ),
        sa.CheckConstraint(
            "actual_qty IS NULL OR actual_qty > 0", name=op.f("ck_production_orders_actual_qty")
        ),
        sa.CheckConstraint("input_value >= 0", name=op.f("ck_production_orders_input_value")),
        sa.CheckConstraint("planned_qty > 0", name=op.f("ck_production_orders_planned_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_production_orders_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_production_orders_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_production_orders_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_orders")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_production_orders_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_production_orders_tenant_id_outlet_id_production_date"),
        "production_orders",
        ["tenant_id", "outlet_id", "production_date"],
        unique=False,
    )
    op.create_table(
        "production_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("planned_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("actual_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("value", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "actual_qty IS NULL OR actual_qty >= 0", name=op.f("ck_production_lines_actual_qty")
        ),
        sa.CheckConstraint("planned_qty >= 0", name=op.f("ck_production_lines_planned_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_production_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["production_orders.tenant_id", "production_orders.id"],
            name=op.f("fk_production_lines_tenant_id_order_id_production_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_production_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_production_lines_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_production_lines_tenant_id_order_id"),
        "production_lines",
        ["tenant_id", "order_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    grant("production_orders", "SELECT, INSERT, UPDATE")  # cancelled or reversed, never deleted
    grant("production_lines", "SELECT, INSERT, UPDATE")
    for table in ("production_orders", "production_lines"):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_lines_tenant_id_order_id"), table_name="production_lines")
    op.drop_table("production_lines")
    op.drop_index(
        op.f("ix_production_orders_tenant_id_outlet_id_production_date"),
        table_name="production_orders",
    )
    op.drop_table("production_orders")
    # ### end Alembic commands ###
