"""stock levels

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-08 15:33:11.726824
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_levels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("par_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("min_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("reorder_point", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("max_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("safety_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "coalesce(par_qty, 0) >= 0 AND coalesce(min_qty, 0) >= 0 AND coalesce(reorder_point, 0) >= 0 AND coalesce(max_qty, 0) >= 0 AND coalesce(safety_qty, 0) >= 0",
            name=op.f("ck_stock_levels_non_negative"),
        ),
        sa.CheckConstraint(
            "lead_time_days IS NULL OR lead_time_days >= 0", name=op.f("ck_stock_levels_lead_time")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_stock_levels_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_stock_levels_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_stock_levels_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_levels")),
        sa.UniqueConstraint(
            "tenant_id",
            "outlet_id",
            "item_id",
            name=op.f("uq_stock_levels_tenant_id_outlet_id_item_id"),
        ),
    )
    # ### end Alembic commands ###
    grant("stock_levels", "SELECT, INSERT, UPDATE, DELETE")  # targets are settings, not ledger
    enable_tenant_rls("stock_levels")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_levels")
    # ### end Alembic commands ###
