"""transfers

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-08 17:05:18.408882
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("from_outlet_id", sa.Uuid(), nullable=False),
        sa.Column("to_outlet_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="requested", nullable=False),
        sa.Column("needed_by", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("shipped_value", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("adjustment_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_by", sa.Uuid(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_on", sa.Date(), nullable=True),
        sa.Column("received_by", sa.Uuid(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_on", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "status IN ('requested', 'approved', 'shipped', 'received', 'cancelled')",
            name=op.f("ck_transfers_status_valid"),
        ),
        sa.CheckConstraint("from_outlet_id <> to_outlet_id", name=op.f("ck_transfers_two_outlets")),
        sa.CheckConstraint("shipped_value >= 0", name=op.f("ck_transfers_shipped_value")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "from_outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_transfers_tenant_id_from_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "to_outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_transfers_tenant_id_to_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_transfers_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfers")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_transfers_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_transfers_tenant_id_from_outlet_id_status"),
        "transfers",
        ["tenant_id", "from_outlet_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transfers_tenant_id_to_outlet_id_status"),
        "transfers",
        ["tenant_id", "to_outlet_id", "status"],
        unique=False,
    )
    op.create_table(
        "transfer_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("requested_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("approved_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("shipped_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("received_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("discrepancy_reason", sa.Text(), nullable=True),
        sa.Column("value", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "discrepancy_reason IS NULL OR discrepancy_reason IN ('short', 'damaged')",
            name=op.f("ck_transfer_lines_discrepancy_reason_valid"),
        ),
        sa.CheckConstraint(
            "approved_qty IS NULL OR approved_qty >= 0", name=op.f("ck_transfer_lines_approved_qty")
        ),
        sa.CheckConstraint(
            "received_qty IS NULL OR received_qty >= 0", name=op.f("ck_transfer_lines_received_qty")
        ),
        sa.CheckConstraint("requested_qty > 0", name=op.f("ck_transfer_lines_requested_qty")),
        sa.CheckConstraint(
            "shipped_qty IS NULL OR shipped_qty >= 0", name=op.f("ck_transfer_lines_shipped_qty")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_transfer_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "transfer_id"],
            ["transfers.tenant_id", "transfers.id"],
            name=op.f("fk_transfer_lines_tenant_id_transfer_id_transfers"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_transfer_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfer_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_transfer_lines_tenant_id_id")),
        sa.UniqueConstraint(
            "transfer_id", "item_id", name=op.f("uq_transfer_lines_transfer_id_item_id")
        ),
    )
    op.create_index(
        op.f("ix_transfer_lines_tenant_id_transfer_id"),
        "transfer_lines",
        ["tenant_id", "transfer_id"],
        unique=False,
    )
    op.create_table(
        "transfer_picks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("lot_code", sa.String(length=64), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.CheckConstraint("qty > 0", name=op.f("ck_transfer_picks_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "line_id"],
            ["transfer_lines.tenant_id", "transfer_lines.id"],
            name=op.f("fk_transfer_picks_tenant_id_line_id_transfer_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "transfer_id"],
            ["transfers.tenant_id", "transfers.id"],
            name=op.f("fk_transfer_picks_tenant_id_transfer_id_transfers"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_transfer_picks_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfer_picks")),
    )
    op.create_index(
        op.f("ix_transfer_picks_tenant_id_transfer_id"),
        "transfer_picks",
        ["tenant_id", "transfer_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    grant("transfers", "SELECT, INSERT, UPDATE")  # cancelled, never deleted
    grant("transfer_lines", "SELECT, INSERT, UPDATE")
    grant("transfer_picks", "SELECT, INSERT")  # what left the source: a record, never changed
    make_append_only("transfer_picks")
    for table in ("transfers", "transfer_lines", "transfer_picks"):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transfer_picks_tenant_id_transfer_id"), table_name="transfer_picks")
    op.drop_table("transfer_picks")
    op.drop_index(op.f("ix_transfer_lines_tenant_id_transfer_id"), table_name="transfer_lines")
    op.drop_table("transfer_lines")
    op.drop_index(op.f("ix_transfers_tenant_id_to_outlet_id_status"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_tenant_id_from_outlet_id_status"), table_name="transfers")
    op.drop_table("transfers")
    # ### end Alembic commands ###
