"""alerts and notifications

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-09 03:13:42.078340
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_notifications_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_tenant_id_user_id_read_at_created_at"),
        "notifications",
        ["tenant_id", "user_id", "read_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("state", sa.Text(), server_default="open", nullable=False),
        sa.Column(
            "raised_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("state IN ('open', 'resolved')", name=op.f("ck_alerts_state_valid")),
        sa.CheckConstraint(
            "type IN ('below_reorder_point', 'low_days_of_inventory', 'batch_near_expiry', 'expired_stock', 'negative_stock', 'count_variance', 'food_cost_above_target', 'approval_requested')",
            name=op.f("ck_alerts_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_alerts_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_alerts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        op.f("ix_alerts_tenant_id_state_raised_at"),
        "alerts",
        ["tenant_id", "state", "raised_at"],
        unique=False,
    )
    op.create_index(
        "uq_alerts_open_key",
        "alerts",
        ["tenant_id", "type", "key"],
        unique=True,
        postgresql_where=sa.text("state = 'open'"),
    )
    # ### end Alembic commands ###
    grant("alerts", "SELECT, INSERT, UPDATE")  # resolved, never deleted
    grant("notifications", "SELECT, INSERT, UPDATE, DELETE")  # deleted after 90 days
    for table in ("alerts", "notifications"):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_alerts_open_key", table_name="alerts", postgresql_where=sa.text("state = 'open'")
    )
    op.drop_index(op.f("ix_alerts_tenant_id_state_raised_at"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(
        op.f("ix_notifications_tenant_id_user_id_read_at_created_at"), table_name="notifications"
    )
    op.drop_table("notifications")
    # ### end Alembic commands ###
