"""food cost target

Revision ID: 0023
Revises: 0022
Create Date: 2026-10-09 03:42:26.357130
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("target_food_cost_bp", sa.Integer(), nullable=True))
    op.create_check_constraint(
        op.f("ck_items_target_food_cost_bp"),
        "items",
        "target_food_cost_bp IS NULL OR (target_food_cost_bp > 0 AND target_food_cost_bp <= 10000)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_items_target_food_cost_bp"), "items", type_="check")
    op.drop_column("items", "target_food_cost_bp")
    # ### end Alembic commands ###
