"""sales days and platform map

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-09 03:54:55.972441
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_days",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("locked_by", sa.Uuid(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('open', 'locked')", name=op.f("ck_sales_days_status_valid")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_sales_days_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_days_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_days")),
        sa.UniqueConstraint(
            "tenant_id",
            "outlet_id",
            "business_date",
            name=op.f("uq_sales_days_tenant_id_outlet_id_business_date"),
        ),
    )
    op.create_table(
        "sales_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("source", sa.Text(), server_default="manual_day", nullable=False),
        sa.Column("status", sa.Text(), server_default="posted", nullable=False),
        sa.Column("subtotal", sa.BigInteger(), nullable=False),
        sa.Column("discount", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("service_charge", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tax", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("cost", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('manual_day', 'pos')", name=op.f("ck_sales_documents_source_valid")
        ),
        sa.CheckConstraint(
            "status IN ('posted', 'replaced', 'reversed')",
            name=op.f("ck_sales_documents_status_valid"),
        ),
        sa.CheckConstraint(
            "discount >= 0 AND service_charge >= 0 AND tax >= 0",
            name=op.f("ck_sales_documents_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["channels.tenant_id", "channels.id"],
            name=op.f("fk_sales_documents_tenant_id_channel_id_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_sales_documents_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_documents_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_documents")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_documents_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_sales_documents_tenant_id_outlet_id_business_date"),
        "sales_documents",
        ["tenant_id", "outlet_id", "business_date"],
        unique=False,
    )
    op.create_index(
        "uq_sales_documents_live_day",
        "sales_documents",
        ["tenant_id", "outlet_id", "channel_id", "business_date"],
        unique=True,
        postgresql_where=sa.text("status = 'posted' AND source = 'manual_day'"),
    )
    op.create_table(
        "platform_item_map",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("platform_code", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["channels.tenant_id", "channels.id"],
            name=op.f("fk_platform_item_map_tenant_id_channel_id_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_platform_item_map_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_platform_item_map_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_item_map")),
        sa.UniqueConstraint(
            "tenant_id",
            "channel_id",
            "platform_code",
            name=op.f("uq_platform_item_map_tenant_id_channel_id_platform_code"),
        ),
    )
    op.create_index(
        op.f("ix_platform_item_map_tenant_id_item_id"),
        "platform_item_map",
        ["tenant_id", "item_id"],
        unique=False,
    )
    op.create_table(
        "sales_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("platform_code", sa.String(length=64), nullable=True),
        sa.Column("bom_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("qty > 0", name=op.f("ck_sales_lines_qty")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sales_lines_unit_price")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name=op.f("fk_sales_lines_tenant_id_document_id_sales_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_sales_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_lines")),
    )
    op.create_index(
        op.f("ix_sales_lines_tenant_id_document_id"),
        "sales_lines",
        ["tenant_id", "document_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    grant("sales_days", "SELECT, INSERT, UPDATE")
    grant("sales_documents", "SELECT, INSERT, UPDATE")  # replaced or reversed, never deleted
    grant("sales_lines", "SELECT, INSERT")  # a posted document's lines never change
    make_append_only("sales_lines")
    grant("platform_item_map", "SELECT, INSERT, UPDATE, DELETE")  # configuration
    for table in ("sales_days", "sales_documents", "sales_lines", "platform_item_map"):
        enable_tenant_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_lines_tenant_id_document_id"), table_name="sales_lines")
    op.drop_table("sales_lines")
    op.drop_index(op.f("ix_platform_item_map_tenant_id_item_id"), table_name="platform_item_map")
    op.drop_table("platform_item_map")
    op.drop_index(
        "uq_sales_documents_live_day",
        table_name="sales_documents",
        postgresql_where=sa.text("status = 'posted' AND source = 'manual_day'"),
    )
    op.drop_index(
        op.f("ix_sales_documents_tenant_id_outlet_id_business_date"), table_name="sales_documents"
    )
    op.drop_table("sales_documents")
    op.drop_table("sales_days")
    # ### end Alembic commands ###
