"""flags job failures admin grants

Revision ID: 0025
Revises: 0024
Create Date: 2026-10-09 04:18:48.708340
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import admin_access, enable_tenant_rls, grant

revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_failures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job", sa.String(length=60), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("error", sa.String(length=200), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_job_failures_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_failures")),
    )
    op.create_table(
        "tenant_flags",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("flag", sa.String(length=60), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tenant_flags_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "flag", name=op.f("pk_tenant_flags")),
    )
    # ### end Alembic commands ###
    op.create_index("ix_job_failures_tenant_id_at", "job_failures", ["tenant_id", "at"])
    # FR-ADM-006: the app reads the tenant's flags; only the platform admin sets them.
    enable_tenant_rls("tenant_flags")
    grant("tenant_flags", "SELECT")
    admin_access("tenant_flags", "SELECT, INSERT, UPDATE")
    # FR-ADM-004: job failures are a platform record; RLS still applies to any tenant role.
    enable_tenant_rls("job_failures")
    admin_access("job_failures", "SELECT, INSERT")
    admin_access("uploads", "SELECT")  # storage per tenant
    admin_access("notifications", "INSERT")  # FR-SUB-006 owner notices from the daily job


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("tenant_flags", "job_failures", "uploads", "notifications"):
        op.execute(f"DROP POLICY IF EXISTS platform_admin ON {table}")
    op.drop_index("ix_job_failures_tenant_id_at", table_name="job_failures")
    op.drop_table("tenant_flags")
    op.drop_table("job_failures")
    # ### end Alembic commands ###
