"""modifiers and availability

Revision ID: 0026
Revises: 0025
Create Date: 2026-10-09 08:37:25.141582
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0026"
down_revision: str | None = "0025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modifier_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("min_select", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_select", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "min_select >= 0 AND max_select >= 1 AND min_select <= max_select",
            name=op.f("ck_modifier_groups_selects"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_modifier_groups_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifier_groups")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_modifier_groups_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_modifier_groups_tenant_id_name")),
    )
    op.create_table(
        "item_modifier_groups",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "group_id"],
            ["modifier_groups.tenant_id", "modifier_groups.id"],
            name=op.f("fk_item_modifier_groups_tenant_id_group_id_modifier_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_item_modifier_groups_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_item_modifier_groups_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "item_id", "group_id", name=op.f("pk_item_modifier_groups")
        ),
    )
    op.create_index(
        op.f("ix_item_modifier_groups_tenant_id_group_id"),
        "item_modifier_groups",
        ["tenant_id", "group_id"],
        unique=False,
    )
    op.create_table(
        "modifier_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_delta", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("ingredient_item_id", sa.Uuid(), nullable=True),
        sa.Column("ingredient_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "(ingredient_item_id IS NULL) = (ingredient_qty IS NULL) AND (ingredient_qty IS NULL OR ingredient_qty <> 0)",
            name=op.f("ck_modifier_options_ingredient"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "group_id"],
            ["modifier_groups.tenant_id", "modifier_groups.id"],
            name=op.f("fk_modifier_options_tenant_id_group_id_modifier_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "ingredient_item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_modifier_options_tenant_id_ingredient_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_modifier_options_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifier_options")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_modifier_options_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_modifier_options_tenant_id_group_id"),
        "modifier_options",
        ["tenant_id", "group_id"],
        unique=False,
    )
    op.add_column(
        "items", sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False)
    )
    grant("modifier_groups", "SELECT, INSERT, UPDATE")
    grant("modifier_options", "SELECT, INSERT, UPDATE")  # switched off, never deleted
    grant("item_modifier_groups", "SELECT, INSERT, UPDATE, DELETE")  # configuration
    for table in ("modifier_groups", "modifier_options", "item_modifier_groups"):
        enable_tenant_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "is_available")
    op.drop_index(op.f("ix_modifier_options_tenant_id_group_id"), table_name="modifier_options")
    op.drop_table("modifier_options")
    op.drop_index(
        op.f("ix_item_modifier_groups_tenant_id_group_id"), table_name="item_modifier_groups"
    )
    op.drop_table("item_modifier_groups")
    op.drop_table("modifier_groups")
    # ### end Alembic commands ###
