"""pos orders payments shifts

Revision ID: 0027
Revises: 0026
Create Date: 2026-10-09 08:48:55.713466
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0027"
down_revision: str | None = "0026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_unique_constraint(
        op.f("uq_sales_lines_tenant_id_id"), "sales_lines", ["tenant_id", "id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_shifts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("cashier_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("opening_float", sa.BigInteger(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Uuid(), nullable=True),
        sa.Column("expected", sa.BigInteger(), nullable=True),
        sa.Column("counted", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_cash_shifts_status_valid")
        ),
        sa.CheckConstraint(
            "opening_float >= 0 AND (counted IS NULL OR counted >= 0)",
            name=op.f("ck_cash_shifts_cash"),
        ),
        sa.ForeignKeyConstraint(
            ["cashier_id"], ["users.id"], name=op.f("fk_cash_shifts_cashier_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_cash_shifts_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_cash_shifts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_shifts")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_cash_shifts_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_cash_shifts_tenant_id_outlet_id_opened_at"),
        "cash_shifts",
        ["tenant_id", "outlet_id", "opened_at"],
        unique=False,
    )
    op.create_index(
        "uq_cash_shifts_open",
        "cash_shifts",
        ["tenant_id", "outlet_id", "cashier_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "cash_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('in', 'out')", name=op.f("ck_cash_movements_kind_valid")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_cash_movements_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "shift_id"],
            ["cash_shifts.tenant_id", "cash_shifts.id"],
            name=op.f("fk_cash_movements_tenant_id_shift_id_cash_shifts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_cash_movements_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
    )
    op.create_index(
        op.f("ix_cash_movements_tenant_id_shift_id"),
        "cash_movements",
        ["tenant_id", "shift_id"],
        unique=False,
    )
    op.create_table(
        "pos_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'paid', 'cancelled', 'void')",
            name=op.f("ck_pos_orders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["channels.tenant_id", "channels.id"],
            name=op.f("fk_pos_orders_tenant_id_channel_id_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name=op.f("fk_pos_orders_tenant_id_document_id_sales_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_pos_orders_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "shift_id"],
            ["cash_shifts.tenant_id", "cash_shifts.id"],
            name=op.f("fk_pos_orders_tenant_id_shift_id_cash_shifts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_pos_orders_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pos_orders")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_pos_orders_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_pos_orders_tenant_id_outlet_id_status"),
        "pos_orders",
        ["tenant_id", "outlet_id", "status"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("method_code", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("tendered", sa.BigInteger(), nullable=True),
        sa.Column("change", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column(
            "paid_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount > 0 AND change >= 0", name=op.f("ck_payments_amounts")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name=op.f("fk_payments_tenant_id_document_id_sales_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["pos_orders.tenant_id", "pos_orders.id"],
            name=op.f("fk_payments_tenant_id_order_id_pos_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "shift_id"],
            ["cash_shifts.tenant_id", "cash_shifts.id"],
            name=op.f("fk_payments_tenant_id_shift_id_cash_shifts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_payments_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(
        op.f("ix_payments_tenant_id_document_id"),
        "payments",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payments_tenant_id_shift_id"), "payments", ["tenant_id", "shift_id"], unique=False
    )
    op.create_table(
        "pos_order_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("status", sa.Text(), server_default="new", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'sent')", name=op.f("ck_pos_order_lines_status_valid")
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_pos_order_lines_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_pos_order_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["pos_orders.tenant_id", "pos_orders.id"],
            name=op.f("fk_pos_order_lines_tenant_id_order_id_pos_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_pos_order_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pos_order_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_pos_order_lines_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_pos_order_lines_tenant_id_order_id"),
        "pos_order_lines",
        ["tenant_id", "order_id"],
        unique=False,
    )
    op.create_table(
        "sales_modifier_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("option_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_delta", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "line_id"],
            ["sales_lines.tenant_id", "sales_lines.id"],
            name=op.f("fk_sales_modifier_lines_tenant_id_line_id_sales_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "option_id"],
            ["modifier_options.tenant_id", "modifier_options.id"],
            name=op.f("fk_sales_modifier_lines_tenant_id_option_id_modifier_options"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_modifier_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_modifier_lines")),
    )
    op.create_index(
        op.f("ix_sales_modifier_lines_tenant_id_line_id"),
        "sales_modifier_lines",
        ["tenant_id", "line_id"],
        unique=False,
    )
    op.create_table(
        "pos_line_modifiers",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("option_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_delta", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "line_id"],
            ["pos_order_lines.tenant_id", "pos_order_lines.id"],
            name=op.f("fk_pos_line_modifiers_tenant_id_line_id_pos_order_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "option_id"],
            ["modifier_options.tenant_id", "modifier_options.id"],
            name=op.f("fk_pos_line_modifiers_tenant_id_option_id_modifier_options"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_pos_line_modifiers_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "line_id", "option_id", name=op.f("pk_pos_line_modifiers")
        ),
    )
    op.add_column(
        "sales_documents", sa.Column("tip", sa.BigInteger(), server_default="0", nullable=False)
    )
    op.add_column(
        "sales_documents",
        sa.Column("rounding", sa.BigInteger(), server_default="0", nullable=False),
    )
    grant("cash_shifts", "SELECT, INSERT, UPDATE")  # closed once, never deleted
    grant("cash_movements", "SELECT, INSERT")
    grant("pos_orders", "SELECT, INSERT, UPDATE")
    grant("pos_order_lines", "SELECT, INSERT, UPDATE, DELETE")  # unsent lines can be removed
    grant("pos_line_modifiers", "SELECT, INSERT, DELETE")
    grant("payments", "SELECT, INSERT")
    grant("sales_modifier_lines", "SELECT, INSERT")
    for table in (
        "cash_shifts",
        "cash_movements",
        "pos_orders",
        "pos_order_lines",
        "pos_line_modifiers",
        "payments",
        "sales_modifier_lines",
    ):
        enable_tenant_rls(table)
    make_append_only("cash_movements")
    make_append_only("payments")
    make_append_only("sales_modifier_lines")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales_documents", "rounding")
    op.drop_column("sales_documents", "tip")
    op.drop_table("pos_line_modifiers")
    op.drop_index(
        op.f("ix_sales_modifier_lines_tenant_id_line_id"), table_name="sales_modifier_lines"
    )
    op.drop_table("sales_modifier_lines")
    op.drop_index(op.f("ix_pos_order_lines_tenant_id_order_id"), table_name="pos_order_lines")
    op.drop_table("pos_order_lines")
    op.drop_index(op.f("ix_payments_tenant_id_shift_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_tenant_id_document_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_pos_orders_tenant_id_outlet_id_status"), table_name="pos_orders")
    op.drop_table("pos_orders")
    op.drop_index(op.f("ix_cash_movements_tenant_id_shift_id"), table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(
        "uq_cash_shifts_open", table_name="cash_shifts", postgresql_where=sa.text("status = 'open'")
    )
    op.drop_index(op.f("ix_cash_shifts_tenant_id_outlet_id_opened_at"), table_name="cash_shifts")
    op.drop_table("cash_shifts")
    # ### end Alembic commands ###
    op.drop_constraint(op.f("uq_sales_lines_tenant_id_id"), "sales_lines", type_="unique")
