"""discounts voids refunds

Revision ID: 0028
Revises: 0027
Create Date: 2026-10-09 09:14:52.061667
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import ADMIN_ROLE, admin_access, enable_tenant_rls, grant

revision: str = "0028"
down_revision: str | None = "0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


DISCOUNT = (
    "(discount_kind IS NULL) = (discount_value IS NULL)"
    " AND (discount_kind IS NULL OR discount_kind IN ('percent', 'amount'))"
    " AND (discount_value IS NULL OR discount_value > 0)"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_refunds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="requested", nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("stock_effect", sa.Text(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method_code", sa.String(length=40), nullable=False),
        sa.Column("method_kind", sa.Text(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('requested', 'done', 'rejected')",
            name=op.f("ck_sales_refunds_status_valid"),
        ),
        sa.CheckConstraint(
            "stock_effect IN ('return', 'waste')", name=op.f("ck_sales_refunds_stock_effect_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_sales_refunds_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name=op.f("fk_sales_refunds_tenant_id_document_id_sales_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["pos_orders.tenant_id", "pos_orders.id"],
            name=op.f("fk_sales_refunds_tenant_id_order_id_pos_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_sales_refunds_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "shift_id"],
            ["cash_shifts.tenant_id", "cash_shifts.id"],
            name=op.f("fk_sales_refunds_tenant_id_shift_id_cash_shifts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_refunds_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_refunds")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_refunds_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_sales_refunds_tenant_id_shift_id"),
        "sales_refunds",
        ["tenant_id", "shift_id"],
        unique=False,
    )
    op.create_index(
        "uq_sales_refunds_live",
        "sales_refunds",
        ["tenant_id", "order_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'rejected'"),
    )
    op.add_column("pos_order_lines", sa.Column("discount_kind", sa.Text(), nullable=True))
    op.add_column("pos_order_lines", sa.Column("discount_value", sa.BigInteger(), nullable=True))
    op.add_column(
        "pos_order_lines", sa.Column("discount_reason", sa.String(length=200), nullable=True)
    )
    op.add_column("pos_order_lines", sa.Column("discount_by", sa.Uuid(), nullable=True))
    op.add_column("pos_order_lines", sa.Column("void_reason", sa.String(length=200), nullable=True))
    op.add_column("pos_order_lines", sa.Column("voided_by", sa.Uuid(), nullable=True))
    op.add_column("pos_orders", sa.Column("discount_kind", sa.Text(), nullable=True))
    op.add_column("pos_orders", sa.Column("discount_value", sa.BigInteger(), nullable=True))
    op.add_column("pos_orders", sa.Column("discount_reason", sa.String(length=200), nullable=True))
    op.add_column("pos_orders", sa.Column("discount_by", sa.Uuid(), nullable=True))
    for table, statuses in (
        ("pos_orders", "'open', 'paid', 'cancelled', 'void', 'refunded'"),
        ("pos_order_lines", "'new', 'sent', 'void'"),
    ):
        # Plain SQL: names stay exactly as the models' naming convention gives them.
        op.execute(
            f"ALTER TABLE {table} DROP CONSTRAINT ck_{table}_status_valid,"
            f" ADD CONSTRAINT ck_{table}_status_valid CHECK (status IN ({statuses})),"
            f" ADD CONSTRAINT ck_{table}_discount CHECK ({DISCOUNT})"
        )
    grant("sales_refunds", "SELECT, INSERT, UPDATE")  # decided once, never deleted
    enable_tenant_rls("sales_refunds")
    admin_access("approval_rules", "SELECT, INSERT")  # default rules at tenant creation
    # docs/03 section 7 default: a manager approves every refund (owners change it in
    # Settings > Approvals). New tenants get the same rule when they are created.
    op.execute(
        "INSERT INTO approval_rules (id, tenant_id, document_type, min_amount, approver_role_id)"
        " SELECT gen_random_uuid(), r.tenant_id, 'refund', 0, r.id FROM roles r"
        " WHERE r.template_key = 'manager' AND r.tenant_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DELETE FROM approval_rules WHERE document_type = 'refund'")
    op.execute("DROP POLICY IF EXISTS platform_admin ON approval_rules")
    op.execute(f"REVOKE SELECT, INSERT ON approval_rules FROM {ADMIN_ROLE}")
    for table, statuses in (
        ("pos_orders", "'open', 'paid', 'cancelled', 'void'"),
        ("pos_order_lines", "'new', 'sent'"),
    ):
        op.execute(
            f"ALTER TABLE {table} DROP CONSTRAINT ck_{table}_discount,"
            f" DROP CONSTRAINT ck_{table}_status_valid,"
            f" ADD CONSTRAINT ck_{table}_status_valid CHECK (status IN ({statuses}))"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pos_orders", "discount_by")
    op.drop_column("pos_orders", "discount_reason")
    op.drop_column("pos_orders", "discount_value")
    op.drop_column("pos_orders", "discount_kind")
    op.drop_column("pos_order_lines", "voided_by")
    op.drop_column("pos_order_lines", "void_reason")
    op.drop_column("pos_order_lines", "discount_by")
    op.drop_column("pos_order_lines", "discount_reason")
    op.drop_column("pos_order_lines", "discount_value")
    op.drop_column("pos_order_lines", "discount_kind")
    op.drop_index(
        "uq_sales_refunds_live",
        table_name="sales_refunds",
        postgresql_where=sa.text("status <> 'rejected'"),
    )
    op.drop_index(op.f("ix_sales_refunds_tenant_id_shift_id"), table_name="sales_refunds")
    op.drop_table("sales_refunds")
    # ### end Alembic commands ###
