"""tables

Revision ID: 0029
Revises: 0028
Create Date: 2026-10-09 09:41:37.281183
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0029"
down_revision: str | None = "0028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_floors_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_floors_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floors")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_floors_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "outlet_id", "name", name=op.f("uq_floors_tenant_id_outlet_id_name")
        ),
    )
    op.create_table(
        "table_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("party_size", sa.Integer(), server_default="1", nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_into", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_table_sessions_status_valid")
        ),
        sa.CheckConstraint("party_size > 0", name=op.f("ck_table_sessions_party_size")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["channels.tenant_id", "channels.id"],
            name=op.f("fk_table_sessions_tenant_id_channel_id_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_table_sessions_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_table_sessions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_table_sessions")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_table_sessions_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_table_sessions_tenant_id_outlet_id_status"),
        "table_sessions",
        ["tenant_id", "outlet_id", "status"],
        unique=False,
    )
    op.create_table(
        "dining_tables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("floor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("capacity", sa.Integer(), server_default="4", nullable=False),
        sa.Column("x", sa.Integer(), server_default="0", nullable=False),
        sa.Column("y", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="available", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "status IN ('available', 'occupied', 'reserved', 'needs_cleaning')",
            name=op.f("ck_dining_tables_status_valid"),
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_dining_tables_capacity")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "floor_id"],
            ["floors.tenant_id", "floors.id"],
            name=op.f("fk_dining_tables_tenant_id_floor_id_floors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_dining_tables_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_dining_tables_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dining_tables")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_dining_tables_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "outlet_id", "name", name=op.f("uq_dining_tables_tenant_id_outlet_id_name")
        ),
    )
    op.create_index(
        op.f("ix_dining_tables_tenant_id_floor_id"),
        "dining_tables",
        ["tenant_id", "floor_id"],
        unique=False,
    )
    op.create_table(
        "table_session_orders",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["pos_orders.tenant_id", "pos_orders.id"],
            name=op.f("fk_table_session_orders_tenant_id_order_id_pos_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["table_sessions.tenant_id", "table_sessions.id"],
            name=op.f("fk_table_session_orders_tenant_id_session_id_table_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_table_session_orders_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "session_id", "order_id", name=op.f("pk_table_session_orders")
        ),
        sa.UniqueConstraint(
            "tenant_id", "order_id", name=op.f("uq_table_session_orders_tenant_id_order_id")
        ),
    )
    op.create_table(
        "table_session_tables",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["table_sessions.tenant_id", "table_sessions.id"],
            name=op.f("fk_table_session_tables_tenant_id_session_id_table_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "table_id"],
            ["dining_tables.tenant_id", "dining_tables.id"],
            name=op.f("fk_table_session_tables_tenant_id_table_id_dining_tables"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_table_session_tables_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "session_id", "table_id", name=op.f("pk_table_session_tables")
        ),
    )
    op.create_index(
        "uq_table_session_tables_active",
        "table_session_tables",
        ["tenant_id", "table_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    for table in ("floors", "dining_tables", "table_sessions", "table_session_tables"):
        grant(table, "SELECT, INSERT, UPDATE")  # switched off or closed, never deleted
    grant("table_session_orders", "SELECT, INSERT, UPDATE")
    for table in (
        "floors",
        "dining_tables",
        "table_sessions",
        "table_session_tables",
        "table_session_orders",
    ):
        enable_tenant_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_table_session_tables_active",
        table_name="table_session_tables",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("table_session_tables")
    op.drop_table("table_session_orders")
    op.drop_index(op.f("ix_dining_tables_tenant_id_floor_id"), table_name="dining_tables")
    op.drop_table("dining_tables")
    op.drop_index(op.f("ix_table_sessions_tenant_id_outlet_id_status"), table_name="table_sessions")
    op.drop_table("table_sessions")
    op.drop_table("floors")
    # ### end Alembic commands ###
