"""kitchen

Revision ID: 0030
Revises: 0029
Create Date: 2026-10-09 09:54:52.649175
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0030"
down_revision: str | None = "0029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kitchen_stations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("category_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_kitchen_stations_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_kitchen_stations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kitchen_stations")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_kitchen_stations_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "outlet_id",
            "name",
            name=op.f("uq_kitchen_stations_tenant_id_outlet_id_name"),
        ),
    )
    op.create_table(
        "kitchen_tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("channel_name", sa.String(length=80), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=True),
        sa.Column("status", sa.Text(), server_default="new", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bumped_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('new', 'preparing', 'ready', 'bumped')",
            name=op.f("ck_kitchen_tickets_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["pos_orders.tenant_id", "pos_orders.id"],
            name=op.f("fk_kitchen_tickets_tenant_id_order_id_pos_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_kitchen_tickets_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "station_id"],
            ["kitchen_stations.tenant_id", "kitchen_stations.id"],
            name=op.f("fk_kitchen_tickets_tenant_id_station_id_kitchen_stations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_kitchen_tickets_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kitchen_tickets")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_kitchen_tickets_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_kitchen_tickets_tenant_id_outlet_id_status"),
        "kitchen_tickets",
        ["tenant_id", "outlet_id", "status"],
        unique=False,
    )
    op.create_table(
        "kitchen_ticket_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("modifiers", sa.Text(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'void')", name=op.f("ck_kitchen_ticket_items_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "line_id"],
            ["pos_order_lines.tenant_id", "pos_order_lines.id"],
            name=op.f("fk_kitchen_ticket_items_tenant_id_line_id_pos_order_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "ticket_id"],
            ["kitchen_tickets.tenant_id", "kitchen_tickets.id"],
            name=op.f("fk_kitchen_ticket_items_tenant_id_ticket_id_kitchen_tickets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_kitchen_ticket_items_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kitchen_ticket_items")),
    )
    op.create_index(
        op.f("ix_kitchen_ticket_items_tenant_id_line_id"),
        "kitchen_ticket_items",
        ["tenant_id", "line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kitchen_ticket_items_tenant_id_ticket_id"),
        "kitchen_ticket_items",
        ["tenant_id", "ticket_id"],
        unique=False,
    )
    grant("kitchen_stations", "SELECT, INSERT, UPDATE")
    grant("kitchen_tickets", "SELECT, INSERT, UPDATE")
    grant("kitchen_ticket_items", "SELECT, INSERT, UPDATE")
    for table in ("kitchen_stations", "kitchen_tickets", "kitchen_ticket_items"):
        enable_tenant_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kitchen_ticket_items_tenant_id_ticket_id"), table_name="kitchen_ticket_items"
    )
    op.drop_index(
        op.f("ix_kitchen_ticket_items_tenant_id_line_id"), table_name="kitchen_ticket_items"
    )
    op.drop_table("kitchen_ticket_items")
    op.drop_index(
        op.f("ix_kitchen_tickets_tenant_id_outlet_id_status"), table_name="kitchen_tickets"
    )
    op.drop_table("kitchen_tickets")
    op.drop_table("kitchen_stations")
    # ### end Alembic commands ###
