"""devices and pins

Revision ID: 0031
Revises: 0030
Create Date: 2026-10-09 10:14:37.389828
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import APP_ROLE, AUTH_ROLE, enable_tenant_rls, grant

revision: str = "0031"
down_revision: str | None = "0030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_pins",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pin_hash", sa.Text(), nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "set_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_user_pins_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_pins_user_id_users")),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", name=op.f("pk_user_pins")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("registered_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["registered_by"], ["users.id"], name=op.f("fk_devices_registered_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_devices_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_devices_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_devices_tenant_id_id")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_devices_token_hash")),
    )
    op.create_index(
        op.f("ix_devices_tenant_id_revoked_at"),
        "devices",
        ["tenant_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "device_users",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "device_id"],
            ["devices.tenant_id", "devices.id"],
            name=op.f("fk_device_users_tenant_id_device_id_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_device_users_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_device_users_user_id_users")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "device_id", "user_id", name=op.f("pk_device_users")),
    )
    grant("devices", "SELECT, INSERT, UPDATE")  # revoked, never deleted
    grant("device_users", "SELECT, INSERT")
    grant("user_pins", "SELECT, INSERT, UPDATE, DELETE")  # a reset removes the PIN
    for table in ("devices", "device_users", "user_pins"):
        enable_tenant_rls(table)
    # FR-IDN-004: find the device by its cookie before any tenant is known. Owned by the
    # BYPASSRLS pos_auth role but returns only the one device whose token hash matches.
    op.execute(f"GRANT SELECT ON devices TO {AUTH_ROLE}")
    op.execute("""
        CREATE FUNCTION auth_device_by_token(p_token_hash bytea)
        RETURNS TABLE (id uuid, tenant_id uuid, outlet_id uuid, name text,
                       revoked_at timestamptz)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
            SELECT d.id, d.tenant_id, d.outlet_id, d.name::text, d.revoked_at
            FROM devices d JOIN tenants t ON t.id = d.tenant_id
            WHERE d.token_hash = p_token_hash AND t.status = 'active'
        $$
    """)
    op.execute(f"ALTER FUNCTION auth_device_by_token(bytea) OWNER TO {AUTH_ROLE}")
    op.execute("REVOKE ALL ON FUNCTION auth_device_by_token(bytea) FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION auth_device_by_token(bytea) TO {APP_ROLE}")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS auth_device_by_token(bytea)")
    op.execute(f"REVOKE SELECT ON devices FROM {AUTH_ROLE}")  # noqa: S608 - constant role name
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_users")
    op.drop_index(op.f("ix_devices_tenant_id_revoked_at"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("user_pins")
    # ### end Alembic commands ###
