"""combos and outlet overrides

Revision ID: 0032
Revises: 0031
Create Date: 2026-10-09 10:24:47.508099
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0032"
down_revision: str | None = "0031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "combo_components",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("combo_item_id", sa.Uuid(), nullable=False),
        sa.Column("component_item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "combo_item_id <> component_item_id", name=op.f("ck_combo_components_not_itself")
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_combo_components_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "combo_item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_combo_components_tenant_id_combo_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "component_item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_combo_components_tenant_id_component_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_combo_components_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "combo_item_id", "component_item_id", name=op.f("pk_combo_components")
        ),
    )
    op.create_index(
        op.f("ix_combo_components_tenant_id_component_item_id"),
        "combo_components",
        ["tenant_id", "component_item_id"],
        unique=False,
    )
    op.create_table(
        "outlet_item_overrides",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_outlet_item_overrides_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_outlet_item_overrides_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_outlet_item_overrides_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "outlet_id", "item_id", name=op.f("pk_outlet_item_overrides")
        ),
    )
    op.create_index(
        op.f("ix_outlet_item_overrides_tenant_id_item_id"),
        "outlet_item_overrides",
        ["tenant_id", "item_id"],
        unique=False,
    )
    grant("combo_components", "SELECT, INSERT, UPDATE, DELETE")  # configuration
    grant("outlet_item_overrides", "SELECT, INSERT, UPDATE, DELETE")
    for table in ("combo_components", "outlet_item_overrides"):
        enable_tenant_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_outlet_item_overrides_tenant_id_item_id"), table_name="outlet_item_overrides"
    )
    op.drop_table("outlet_item_overrides")
    op.drop_index(
        op.f("ix_combo_components_tenant_id_component_item_id"), table_name="combo_components"
    )
    op.drop_table("combo_components")
    # ### end Alembic commands ###
