"""finance lite

Revision ID: 0033
Revises: 0032
Create Date: 2026-10-09 13:50:35.470252
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0033"
down_revision: str | None = "0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_expense_categories_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_expense_categories_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_expense_categories_tenant_id_name")),
    )
    op.create_table(
        "money_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=True),
        sa.Column("opening_balance", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "kind IN ('cash', 'bank', 'petty_cash')", name=op.f("ck_money_accounts_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_money_accounts_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_money_accounts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_money_accounts")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_money_accounts_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_money_accounts_tenant_id_name")),
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("spent_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("payee", sa.String(length=120), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("upload_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), server_default="posted", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reversed_by", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('posted', 'reversed')", name=op.f("ck_expenses_status_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expenses_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "account_id"],
            ["money_accounts.tenant_id", "money_accounts.id"],
            name=op.f("fk_expenses_tenant_id_account_id_money_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["expense_categories.tenant_id", "expense_categories.id"],
            name=op.f("fk_expenses_tenant_id_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_expenses_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "upload_id"],
            ["uploads.tenant_id", "uploads.id"],
            name=op.f("fk_expenses_tenant_id_upload_id_uploads"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_expenses_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_expenses_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_expenses_tenant_id_outlet_id_spent_on"),
        "expenses",
        ["tenant_id", "outlet_id", "spent_on"],
        unique=False,
    )
    op.create_table(
        "money_transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("from_account_id", sa.Uuid(), nullable=False),
        sa.Column("to_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("moved_on", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0 AND from_account_id <> to_account_id", name=op.f("ck_money_transfers_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "from_account_id"],
            ["money_accounts.tenant_id", "money_accounts.id"],
            name=op.f("fk_money_transfers_tenant_id_from_account_id_money_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "to_account_id"],
            ["money_accounts.tenant_id", "money_accounts.id"],
            name=op.f("fk_money_transfers_tenant_id_to_account_id_money_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_money_transfers_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_money_transfers")),
    )
    op.create_index(
        op.f("ix_money_transfers_tenant_id_moved_on"),
        "money_transfers",
        ["tenant_id", "moved_on"],
        unique=False,
    )
    grant("money_accounts", "SELECT, INSERT, UPDATE")
    grant("expense_categories", "SELECT, INSERT, UPDATE")
    grant("expenses", "SELECT, INSERT, UPDATE")  # reversed, never deleted
    grant("money_transfers", "SELECT, INSERT")
    for table in ("money_accounts", "expense_categories", "expenses", "money_transfers"):
        enable_tenant_rls(table)
    make_append_only("money_transfers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_money_transfers_tenant_id_moved_on"), table_name="money_transfers")
    op.drop_table("money_transfers")
    op.drop_index(op.f("ix_expenses_tenant_id_outlet_id_spent_on"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_table("money_accounts")
    op.drop_table("expense_categories")
    # ### end Alembic commands ###
