"""lot trace indexes

Revision ID: 0034
Revises: 0033
Create Date: 2026-10-09 16:45:34.730697
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0034"
down_revision: str | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_stock_batches_tenant_id_source_doc_type_source_doc_id"),
        "stock_batches",
        ["tenant_id", "source_doc_type", "source_doc_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_tenant_id_batch_id"),
        "stock_movements",
        ["tenant_id", "batch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_movements_tenant_id_batch_id"), table_name="stock_movements")
    op.drop_index(
        op.f("ix_stock_batches_tenant_id_source_doc_type_source_doc_id"), table_name="stock_batches"
    )
    # ### end Alembic commands ###
