"""accounts payable

Revision ID: 0035
Revises: 0034
Create Date: 2026-10-09 16:52:43.264680
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0035"
down_revision: str | None = "0034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_bills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_invoice_no", sa.String(length=80), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=True),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("paid", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("credited", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("match_status", sa.Text(), nullable=False),
        sa.Column(
            "match_notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_status IN ('matched', 'mismatch', 'no_po')",
            name=op.f("ck_vendor_bills_match_status_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'partially_paid', 'paid', 'void')",
            name=op.f("ck_vendor_bills_status_valid"),
        ),
        sa.CheckConstraint("paid + credited <= total", name=op.f("ck_vendor_bills_not_overpaid")),
        sa.CheckConstraint("paid >= 0 AND credited >= 0", name=op.f("ck_vendor_bills_settled")),
        sa.CheckConstraint("total >= 0", name=op.f("ck_vendor_bills_total")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_vendor_bills_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "po_id"],
            ["purchase_orders.tenant_id", "purchase_orders.id"],
            name=op.f("fk_vendor_bills_tenant_id_po_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "vendor_id"],
            ["vendors.tenant_id", "vendors.id"],
            name=op.f("fk_vendor_bills_tenant_id_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_bills_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bills")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendor_bills_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "vendor_id",
            "vendor_invoice_no",
            name=op.f("uq_vendor_bills_tenant_id_vendor_id_vendor_invoice_no"),
        ),
    )
    op.create_index(
        op.f("ix_vendor_bills_tenant_id_status_due_date"),
        "vendor_bills",
        ["tenant_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_bills_tenant_id_vendor_id"),
        "vendor_bills",
        ["tenant_id", "vendor_id"],
        unique=False,
    )
    op.create_table(
        "vendor_bill_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_vendor_bill_lines_amount")),
        sa.CheckConstraint("qty > 0", name=op.f("ck_vendor_bill_lines_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bill_id"],
            ["vendor_bills.tenant_id", "vendor_bills.id"],
            name=op.f("fk_vendor_bill_lines_tenant_id_bill_id_vendor_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_vendor_bill_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_bill_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bill_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendor_bill_lines_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_vendor_bill_lines_tenant_id_bill_id"),
        "vendor_bill_lines",
        ["tenant_id", "bill_id"],
        unique=False,
    )
    op.create_table(
        "vendor_bill_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bill_id"],
            ["vendor_bills.tenant_id", "vendor_bills.id"],
            name=op.f("fk_vendor_bill_receipts_tenant_id_bill_id_vendor_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receipt_id"],
            ["goods_receipts.tenant_id", "goods_receipts.id"],
            name=op.f("fk_vendor_bill_receipts_tenant_id_receipt_id_goods_receipts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_bill_receipts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bill_receipts")),
    )
    op.create_index(
        op.f("ix_vendor_bill_receipts_tenant_id_bill_id"),
        "vendor_bill_receipts",
        ["tenant_id", "bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_bill_receipts_tenant_id_receipt_id"),
        "vendor_bill_receipts",
        ["tenant_id", "receipt_id"],
        unique=False,
    )
    op.create_table(
        "vendor_payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("reverses_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_vendor_payments_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bill_id"],
            ["vendor_bills.tenant_id", "vendor_bills.id"],
            name=op.f("fk_vendor_payments_tenant_id_bill_id_vendor_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reverses_id"],
            ["vendor_payments.tenant_id", "vendor_payments.id"],
            name=op.f("fk_vendor_payments_tenant_id_reverses_id_vendor_payments"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_payments_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_payments")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendor_payments_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "reverses_id", name=op.f("uq_vendor_payments_tenant_id_reverses_id")
        ),
    )
    op.create_index(
        op.f("ix_vendor_payments_tenant_id_bill_id"),
        "vendor_payments",
        ["tenant_id", "bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_payments_tenant_id_paid_on"),
        "vendor_payments",
        ["tenant_id", "paid_on"],
        unique=False,
    )
    op.create_table(
        "vendor_returns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=True),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="posted", nullable=False),
        sa.Column("stock_value", sa.BigInteger(), nullable=False),
        sa.Column("credit_amount", sa.BigInteger(), nullable=False),
        sa.Column("credit_note_number", sa.String(length=80), nullable=True),
        sa.Column("credited_on", sa.Date(), nullable=True),
        sa.Column("applied_bill_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('damaged', 'expired', 'wrong_item', 'quality', 'other')",
            name=op.f("ck_vendor_returns_reason_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('posted', 'reversed')", name=op.f("ck_vendor_returns_status_valid")
        ),
        sa.CheckConstraint("credit_amount >= 0", name=op.f("ck_vendor_returns_credit_amount")),
        sa.CheckConstraint("stock_value >= 0", name=op.f("ck_vendor_returns_stock_value")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "applied_bill_id"],
            ["vendor_bills.tenant_id", "vendor_bills.id"],
            name=op.f("fk_vendor_returns_tenant_id_applied_bill_id_vendor_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_vendor_returns_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receipt_id"],
            ["goods_receipts.tenant_id", "goods_receipts.id"],
            name=op.f("fk_vendor_returns_tenant_id_receipt_id_goods_receipts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "vendor_id"],
            ["vendors.tenant_id", "vendors.id"],
            name=op.f("fk_vendor_returns_tenant_id_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_returns_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_returns")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendor_returns_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_vendor_returns_tenant_id_outlet_id_business_date"),
        "vendor_returns",
        ["tenant_id", "outlet_id", "business_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_returns_tenant_id_vendor_id_status"),
        "vendor_returns",
        ["tenant_id", "vendor_id", "status"],
        unique=False,
    )
    op.create_table(
        "vendor_return_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("credit_amount", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("credit_amount >= 0", name=op.f("ck_vendor_return_lines_credit_amount")),
        sa.CheckConstraint("qty > 0", name=op.f("ck_vendor_return_lines_qty")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "batch_id"],
            ["stock_batches.tenant_id", "stock_batches.id"],
            name=op.f("fk_vendor_return_lines_tenant_id_batch_id_stock_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_vendor_return_lines_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "return_id"],
            ["vendor_returns.tenant_id", "vendor_returns.id"],
            name=op.f("fk_vendor_return_lines_tenant_id_return_id_vendor_returns"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vendor_return_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_return_lines")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vendor_return_lines_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_vendor_return_lines_tenant_id_return_id"),
        "vendor_return_lines",
        ["tenant_id", "return_id"],
        unique=False,
    )
    grant("vendor_returns", "SELECT, INSERT, UPDATE")  # reversed, credit note recorded
    grant("vendor_return_lines", "SELECT, INSERT, UPDATE")  # credit set after stock moves
    grant("vendor_bills", "SELECT, INSERT, UPDATE")  # paid totals and status
    grant("vendor_bill_lines", "SELECT, INSERT")
    grant("vendor_bill_receipts", "SELECT, INSERT")
    grant("vendor_payments", "SELECT, INSERT")
    for table in (
        "vendor_returns",
        "vendor_return_lines",
        "vendor_bills",
        "vendor_bill_lines",
        "vendor_bill_receipts",
        "vendor_payments",
    ):
        enable_tenant_rls(table)
    make_append_only("vendor_payments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vendor_return_lines_tenant_id_return_id"), table_name="vendor_return_lines"
    )
    op.drop_table("vendor_return_lines")
    op.drop_index(op.f("ix_vendor_returns_tenant_id_vendor_id_status"), table_name="vendor_returns")
    op.drop_index(
        op.f("ix_vendor_returns_tenant_id_outlet_id_business_date"), table_name="vendor_returns"
    )
    op.drop_table("vendor_returns")
    op.drop_index(op.f("ix_vendor_payments_tenant_id_paid_on"), table_name="vendor_payments")
    op.drop_index(op.f("ix_vendor_payments_tenant_id_bill_id"), table_name="vendor_payments")
    op.drop_table("vendor_payments")
    op.drop_index(
        op.f("ix_vendor_bill_receipts_tenant_id_receipt_id"), table_name="vendor_bill_receipts"
    )
    op.drop_index(
        op.f("ix_vendor_bill_receipts_tenant_id_bill_id"), table_name="vendor_bill_receipts"
    )
    op.drop_table("vendor_bill_receipts")
    op.drop_index(op.f("ix_vendor_bill_lines_tenant_id_bill_id"), table_name="vendor_bill_lines")
    op.drop_table("vendor_bill_lines")
    op.drop_index(op.f("ix_vendor_bills_tenant_id_vendor_id"), table_name="vendor_bills")
    op.drop_index(op.f("ix_vendor_bills_tenant_id_status_due_date"), table_name="vendor_bills")
    op.drop_table("vendor_bills")
    # ### end Alembic commands ###
