"""session device

Revision ID: 0036
Revises: 0035
Create Date: 2026-10-09 17:55:39.092241
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0036"
down_revision: str | None = "0035"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("device_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_sessions_device_id"), "sessions", ["device_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_device_id"), table_name="sessions")
    op.drop_column("sessions", "device_id")
    # ### end Alembic commands ###
