"""expense category account

Revision ID: 0040
Revises: 0039
Create Date: 2026-10-10 08:34:55.089559
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0040"
down_revision: str | None = "0039"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expense_categories", sa.Column("gl_account_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expense_categories", "gl_account_id")
    # ### end Alembic commands ###
