"""wholesale receivables

Revision ID: 0041
Revises: 0040
Create Date: 2026-10-10 08:59:41.493577
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant, make_append_only

revision: str = "0041"
down_revision: str | None = "0040"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receivables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("paid", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'partially_paid', 'paid', 'void')",
            name=op.f("ck_receivables_status_valid"),
        ),
        sa.CheckConstraint("paid >= 0 AND paid <= total", name=op.f("ck_receivables_paid")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_receivables_tenant_id_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name=op.f("fk_receivables_tenant_id_document_id_sales_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_receivables_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_receivables_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivables")),
        sa.UniqueConstraint(
            "tenant_id", "document_id", name=op.f("uq_receivables_tenant_id_document_id")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_receivables_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_receivables_tenant_id_customer_id"),
        "receivables",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receivables_tenant_id_status_due_date"),
        "receivables",
        ["tenant_id", "status", "due_date"],
        unique=False,
    )
    op.create_table(
        "receivable_payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_id", sa.Uuid(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("reverses_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_receivable_payments_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receivable_id"],
            ["receivables.tenant_id", "receivables.id"],
            name=op.f("fk_receivable_payments_tenant_id_receivable_id_receivables"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reverses_id"],
            ["receivable_payments.tenant_id", "receivable_payments.id"],
            name=op.f("fk_receivable_payments_tenant_id_reverses_id_receivable_payments"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_receivable_payments_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivable_payments")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_receivable_payments_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "reverses_id", name=op.f("uq_receivable_payments_tenant_id_reverses_id")
        ),
    )
    op.create_index(
        op.f("ix_receivable_payments_tenant_id_receivable_id"),
        "receivable_payments",
        ["tenant_id", "receivable_id"],
        unique=False,
    )
    grant("receivables", "SELECT, INSERT, UPDATE")  # paid total and status
    grant("receivable_payments", "SELECT, INSERT")
    for table in ("receivables", "receivable_payments"):
        enable_tenant_rls(table)
    make_append_only("receivable_payments")
    op.drop_constraint(op.f("ck_sales_documents_source_valid"), "sales_documents", type_="check")
    op.create_check_constraint(
        op.f("ck_sales_documents_source_valid"),
        "sales_documents",
        "source IN ('manual_day', 'pos', 'wholesale')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_sales_documents_source_valid"), "sales_documents", type_="check")
    op.create_check_constraint(
        op.f("ck_sales_documents_source_valid"),
        "sales_documents",
        "source IN ('manual_day', 'pos')",
    )
    op.drop_index(
        op.f("ix_receivable_payments_tenant_id_receivable_id"), table_name="receivable_payments"
    )
    op.drop_table("receivable_payments")
    op.drop_index(op.f("ix_receivables_tenant_id_status_due_date"), table_name="receivables")
    op.drop_index(op.f("ix_receivables_tenant_id_customer_id"), table_name="receivables")
    op.drop_table("receivables")
    # ### end Alembic commands ###
