"""storage locations and barcodes

Revision ID: 0043
Revises: 0042
Create Date: 2026-10-10 10:57:42.346004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0043"
down_revision: str | None = "0042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_storage_locations_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_storage_locations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_locations")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_storage_locations_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "outlet_id",
            "name",
            name=op.f("uq_storage_locations_tenant_id_outlet_id_name"),
        ),
    )
    op.create_table(
        "item_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "item_id"],
            ["items.tenant_id", "items.id"],
            name=op.f("fk_item_locations_tenant_id_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "location_id"],
            ["storage_locations.tenant_id", "storage_locations.id"],
            name=op.f("fk_item_locations_tenant_id_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_item_locations_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_item_locations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_locations")),
        sa.UniqueConstraint(
            "tenant_id",
            "outlet_id",
            "item_id",
            name=op.f("uq_item_locations_tenant_id_outlet_id_item_id"),
        ),
    )
    op.create_index(
        op.f("ix_item_locations_tenant_id_location_id"),
        "item_locations",
        ["tenant_id", "location_id"],
        unique=False,
    )
    op.add_column("items", sa.Column("barcode", sa.String(length=64), nullable=True))
    op.create_unique_constraint(
        op.f("uq_items_tenant_id_barcode"), "items", ["tenant_id", "barcode"]
    )
    op.add_column("stock_counts", sa.Column("location_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_stock_counts_tenant_id_location_id_storage_locations"),
        "stock_counts",
        "storage_locations",
        ["tenant_id", "location_id"],
        ["tenant_id", "id"],
    )
    grant("storage_locations", "SELECT, INSERT, UPDATE")  # renamed or switched off
    grant("item_locations", "SELECT, INSERT, UPDATE, DELETE")  # where an item is kept
    for table in ("storage_locations", "item_locations"):
        enable_tenant_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stock_counts_tenant_id_location_id_storage_locations"),
        "stock_counts",
        type_="foreignkey",
    )
    op.drop_column("stock_counts", "location_id")
    op.drop_constraint(op.f("uq_items_tenant_id_barcode"), "items", type_="unique")
    op.drop_column("items", "barcode")
    op.drop_index(op.f("ix_item_locations_tenant_id_location_id"), table_name="item_locations")
    op.drop_table("item_locations")
    op.drop_table("storage_locations")
    # ### end Alembic commands ###
