"""data exports and restore requests

Revision ID: 0046
Revises: 0045
Create Date: 2026-10-10 14:13:39.555931
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import admin_access, enable_tenant_rls, grant

revision: str = "0046"
down_revision: str | None = "0045"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("requested_by_admin", sa.Uuid(), nullable=True),
        sa.Column("file_key", sa.String(length=120), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'ready', 'failed')", name=op.f("ck_data_exports_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_data_exports_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_exports")),
    )
    op.create_index(
        op.f("ix_data_exports_tenant_id_created_at"),
        "data_exports",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "restore_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("restore_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="requested", nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_restore_requests_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restore_requests")),
    )
    op.create_index(
        op.f("ix_restore_requests_tenant_id_requested_at"),
        "restore_requests",
        ["tenant_id", "requested_at"],
        unique=False,
    )
    grant("data_exports", "SELECT, INSERT, UPDATE")  # queued -> ready or failed
    enable_tenant_rls("data_exports")
    admin_access("data_exports", "SELECT, INSERT")  # FR-ADM-007: admin starts an export
    enable_tenant_rls("restore_requests")  # platform table: the app role has no grant
    admin_access("restore_requests", "SELECT, INSERT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_restore_requests_tenant_id_requested_at"), table_name="restore_requests")
    op.drop_table("restore_requests")
    op.drop_index(op.f("ix_data_exports_tenant_id_created_at"), table_name="data_exports")
    op.drop_table("data_exports")
    # ### end Alembic commands ###
