"""offline orders; transfer request alerts

Revision ID: 0049
Revises: 0048
Create Date: 2026-10-10 16:06:24.559991
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

OLD = (
    "'below_reorder_point', 'low_days_of_inventory', 'batch_near_expiry', 'expired_stock', "
    "'negative_stock', 'count_variance', 'food_cost_above_target', 'approval_requested'"
)
NEW = OLD + ", 'transfer_requested'"
CHECKS = (("alert_rules", "alert_type"), ("alerts", "type"))


def _checks(values: str) -> None:
    for table, column in CHECKS:
        name = f"{column}_valid"
        op.drop_constraint(name, table, type_="check")
        op.create_check_constraint(name, table, f"{column} IN ({values})")


revision: str = "0049"
down_revision: str | None = "0048"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pos_orders", sa.Column("client_id", sa.Uuid(), nullable=True))
    op.add_column("pos_orders", sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("pos_orders", sa.Column("sync_problem", sa.Text(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_pos_orders_tenant_id_client_id"), "pos_orders", ["tenant_id", "client_id"]
    )
    # ### end Alembic commands ###
    _checks(NEW)


def downgrade() -> None:
    _checks(OLD)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_pos_orders_tenant_id_client_id"), "pos_orders", type_="unique")
    op.drop_column("pos_orders", "sync_problem")
    op.drop_column("pos_orders", "taken_at")
    op.drop_column("pos_orders", "client_id")
    # ### end Alembic commands ###
