"""outlet modules

Revision ID: 0050
Revises: 0049
Create Date: 2026-10-10 16:18:41.072054
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0050"
down_revision: str | None = "0049"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outlet_modules_off",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_outlet_modules_off_tenant_id_outlet_id_outlets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_outlet_modules_off_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "outlet_id", "module", name=op.f("pk_outlet_modules_off")
        ),
    )
    # ### end Alembic commands ###
    grant("outlet_modules_off", "SELECT, INSERT, DELETE")
    enable_tenant_rls("outlet_modules_off")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outlet_modules_off")
    # ### end Alembic commands ###
