"""budgets

Revision ID: 0052
Revises: 0051
Create Date: 2026-10-10 17:36:18.986770
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0052"
down_revision: str | None = "0051"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("net_sales", sa.BigInteger(), nullable=False),
        sa.Column("cost_of_sales", sa.BigInteger(), nullable=False),
        sa.Column("labor", sa.BigInteger(), nullable=False),
        sa.Column("expenses", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("extract(day from month) = 1", name=op.f("ck_budgets_first_of_month")),
        sa.CheckConstraint(
            "net_sales >= 0 AND cost_of_sales >= 0 AND labor >= 0 AND expenses >= 0",
            name=op.f("ck_budgets_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "outlet_id"],
            ["outlets.tenant_id", "outlets.id"],
            name=op.f("fk_budgets_tenant_id_outlet_id_outlets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_budgets_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint(
            "tenant_id", "outlet_id", "month", name=op.f("uq_budgets_tenant_id_outlet_id_month")
        ),
    )
    grant("budgets", "SELECT, INSERT, UPDATE")  # a month's plan is replaced on save
    enable_tenant_rls("budgets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("budgets")
    # ### end Alembic commands ###
