"""loyalty

Revision ID: 0053
Revises: 0052
Create Date: 2026-10-10 17:52:33.665638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.helpers import enable_tenant_rls, grant

revision: str = "0053"
down_revision: str | None = "0052"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loyalty_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("points", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("voucher_id", sa.Uuid(), nullable=True),
        sa.Column("outlet_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('earn', 'redeem', 'reverse', 'adjust')",
            name=op.f("ck_loyalty_entries_kind_valid"),
        ),
        sa.CheckConstraint("points <> 0", name=op.f("ck_loyalty_entries_points")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_loyalty_entries_tenant_id_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_loyalty_entries_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_entries")),
    )
    op.create_index(
        op.f("ix_loyalty_entries_tenant_id_customer_id_created_at"),
        "loyalty_entries",
        ["tenant_id", "customer_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_loyalty_entries_document",
        "loyalty_entries",
        ["tenant_id", "document_id", "kind"],
        unique=True,
        postgresql_where=sa.text("document_id IS NOT NULL"),
    )
    op.create_table(
        "vouchers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("points", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("used_document_id", sa.Uuid(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'used', 'void')", name=op.f("ck_vouchers_status_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_vouchers_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_vouchers_tenant_id_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_vouchers_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vouchers")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_vouchers_tenant_id_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_vouchers_tenant_id_id")),
    )
    grant("loyalty_entries", "SELECT, INSERT")  # append-only points ledger
    enable_tenant_rls("loyalty_entries")
    grant("vouchers", "SELECT, INSERT, UPDATE")  # status moves active -> used or void
    enable_tenant_rls("vouchers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vouchers")
    op.drop_index(
        "uq_loyalty_entries_document",
        table_name="loyalty_entries",
        postgresql_where=sa.text("document_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_loyalty_entries_tenant_id_customer_id_created_at"), table_name="loyalty_entries"
    )
    op.drop_table("loyalty_entries")
    # ### end Alembic commands ###
