"""Core identity and tenancy tables (docs/05 section 2.1, FR-TEN-001, FR-TEN-002).

Conventions (docs/05 section 1): UUIDv7 primary keys generated by the server; every
tenant-owned table has tenant_id, a leading tenant_id index and RLS (see migrations);
critical references use composite (tenant_id, id) foreign keys so a row can never point at
another tenant's row; status columns are text with a CHECK constraint.
"""

import uuid
from datetime import datetime, time
from typing import Any, ClassVar

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import CITEXT, INET, JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.ids import uuid7

# Stable constraint names make migrations reviewable and reversible.
NAMING = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING)
    # All timestamps are timestamptz (stored in UTC, FR-X-002).
    type_annotation_map: ClassVar[dict[Any, Any]] = {datetime: DateTime(timezone=True)}


def _id() -> Mapped[uuid.UUID]:
    return mapped_column(primary_key=True, default=uuid7)


def _created_at() -> Mapped[datetime]:
    return mapped_column(server_default=func.now())


def _check_in(column: str, values: tuple[str, ...]) -> CheckConstraint:
    quoted = ", ".join(f"'{v}'" for v in values)
    return CheckConstraint(f"{column} IN ({quoted})", name=f"{column}_valid")


TENANT_PROFILES = ("restaurant", "cloud_kitchen", "central_kitchen_group", "hybrid")
TENANT_STATUSES = ("active", "suspended", "deleted")
OUTLET_TYPES = ("restaurant", "branch", "cloud_kitchen", "central_kitchen", "warehouse")
USER_STATUSES = ("active", "disabled")
MEMBERSHIP_SCOPES = ("all", "outlets")
MEMBERSHIP_STATUSES = ("active", "invited", "disabled")


class Tenant(Base):
    """FR-TEN-001. RLS: a tenant context sees only its own row (policy on id)."""

    __tablename__ = "tenants"
    __table_args__ = (
        _check_in("profile", TENANT_PROFILES),
        _check_in("status", TENANT_STATUSES),
        CheckConstraint("currency ~ '^[A-Z]{3}$'", name="currency_iso"),
        CheckConstraint("country ~ '^[A-Z]{2}$'", name="country_iso"),
    )

    id: Mapped[uuid.UUID] = _id()
    name: Mapped[str] = mapped_column(String(200))  # display name
    legal_name: Mapped[str] = mapped_column(String(200))
    country: Mapped[str] = mapped_column(String(2))
    currency: Mapped[str] = mapped_column(String(3))
    language: Mapped[str] = mapped_column(String(10))
    timezone: Mapped[str] = mapped_column(String(64))
    profile: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, server_default="active")
    created_at: Mapped[datetime] = _created_at()


class Outlet(Base):
    """FR-TEN-002."""

    __tablename__ = "outlets"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id"),  # target of composite foreign keys
        _check_in("type", OUTLET_TYPES),
        Index(None, "tenant_id", "is_active"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str] = mapped_column(String(200))
    type: Mapped[str] = mapped_column(Text)
    address: Mapped[str | None] = mapped_column(Text)
    timezone: Mapped[str] = mapped_column(String(64))
    day_cutoff: Mapped[time] = mapped_column(server_default="04:00")  # Q-015 default
    is_active: Mapped[bool] = mapped_column(server_default="true")
    created_at: Mapped[datetime] = _created_at()


class User(Base):
    """Global identity: one person can belong to several tenants (FR-IDN-005). Not
    tenant-scoped, so no RLS; only the identity service touches it (slice 0.4)."""

    __tablename__ = "users"
    __table_args__ = (_check_in("status", USER_STATUSES),)

    id: Mapped[uuid.UUID] = _id()
    email: Mapped[str] = mapped_column(CITEXT, unique=True)  # case-insensitive uniqueness
    name: Mapped[str] = mapped_column(String(200))
    password_hash: Mapped[str | None] = mapped_column(Text)  # Argon2id, slice 0.4
    totp_secret_encrypted: Mapped[bytes | None] = mapped_column()  # slice 0.4
    locale: Mapped[str] = mapped_column(String(10), server_default="id")
    status: Mapped[str] = mapped_column(Text, server_default="active")
    created_at: Mapped[datetime] = _created_at()


class Role(Base):
    """tenant_id is NULL for platform templates; tenants get their own copies (slice 0.5)."""

    __tablename__ = "roles"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id"),
        UniqueConstraint("tenant_id", "name"),
        CheckConstraint("is_template = (tenant_id IS NULL)", name="template_has_no_tenant"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str] = mapped_column(String(100))
    is_template: Mapped[bool] = mapped_column(server_default="false")
    created_at: Mapped[datetime] = _created_at()


class RolePermission(Base):
    """tenant_id is copied from the role so RLS can apply without a join (docs/05 rule:
    every tenant-owned table carries tenant_id)."""

    __tablename__ = "role_permissions"
    __table_args__ = (
        ForeignKeyConstraint(["tenant_id", "role_id"], ["roles.tenant_id", "roles.id"]),
        UniqueConstraint("tenant_id", "role_id", "permission_code"),
        CheckConstraint(
            r"permission_code ~ '^[a-z_]+\.[a-z_]+\.[a-z_]+$'", name="permission_code_format"
        ),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID | None] = mapped_column()
    role_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("roles.id", ondelete="CASCADE"))
    permission_code: Mapped[str] = mapped_column(String(100))
    limit_value: Mapped[int | None] = mapped_column()  # e.g. max discount %, approval amount


class Membership(Base):
    __tablename__ = "memberships"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id"),
        UniqueConstraint("tenant_id", "user_id"),  # one row per user per tenant
        ForeignKeyConstraint(["tenant_id", "role_id"], ["roles.tenant_id", "roles.id"]),
        _check_in("scope", MEMBERSHIP_SCOPES),
        _check_in("status", MEMBERSHIP_STATUSES),
        Index(None, "user_id"),  # "which tenants am I in" (slice 0.4)
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"))
    role_id: Mapped[uuid.UUID] = mapped_column()
    scope: Mapped[str] = mapped_column(Text, server_default="all")
    status: Mapped[str] = mapped_column(Text, server_default="active")
    created_at: Mapped[datetime] = _created_at()


class MembershipOutlet(Base):
    __tablename__ = "membership_outlets"
    __table_args__ = (
        ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(["tenant_id", "outlet_id"], ["outlets.tenant_id", "outlets.id"]),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    membership_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    outlet_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)


class AuditLog(Base):
    """FR-AUD-001/002. Append-only: UPDATE/DELETE/TRUNCATE are revoked from the app role and
    a trigger rejects them for everyone else too."""

    __tablename__ = "audit_log"
    __table_args__ = (
        Index(None, "tenant_id", "at"),
        Index(None, "tenant_id", "target_type", "target_id"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    at: Mapped[datetime] = mapped_column(server_default=func.now())
    user_id: Mapped[uuid.UUID | None] = mapped_column()
    actor_type: Mapped[str] = mapped_column(Text, server_default="user")  # user, admin, system
    outlet_id: Mapped[uuid.UUID | None] = mapped_column()
    action: Mapped[str] = mapped_column(String(100))
    target_type: Mapped[str | None] = mapped_column(String(100))
    target_id: Mapped[uuid.UUID | None] = mapped_column()
    summary: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default="{}")
    request_id: Mapped[str | None] = mapped_column(String(64))
    ip: Mapped[str | None] = mapped_column(INET)


class IdempotencyKey(Base):
    """FR-X-003 storage. Rows older than the retention window are pruned by a job."""

    __tablename__ = "idempotency_keys"
    __table_args__ = (UniqueConstraint("tenant_id", "key"),)

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    key: Mapped[uuid.UUID] = mapped_column()
    request_hash: Mapped[str] = mapped_column(String(64))
    response_status: Mapped[int | None] = mapped_column()
    response_body: Mapped[Any | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = _created_at()
