"""Core identity and tenancy tables (docs/05 section 2.1, FR-TEN-001, FR-TEN-002).

Conventions (docs/05 section 1): UUIDv7 primary keys generated by the server; every
tenant-owned table has tenant_id, a leading tenant_id index and RLS (see migrations);
critical references use composite (tenant_id, id) foreign keys so a row can never point at
another tenant's row; status columns are text with a CHECK constraint.
"""

import uuid
from datetime import datetime, time
from typing import Any, ClassVar

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, CITEXT, INET, JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.ids import uuid7

# Stable constraint names make migrations reviewable and reversible.
NAMING = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING)
    # All timestamps are timestamptz (stored in UTC, FR-X-002).
    type_annotation_map: ClassVar[dict[Any, Any]] = {datetime: DateTime(timezone=True)}


def _id() -> Mapped[uuid.UUID]:
    return mapped_column(primary_key=True, default=uuid7)


def _created_at() -> Mapped[datetime]:
    return mapped_column(server_default=func.now())


def _check_in(column: str, values: tuple[str, ...]) -> CheckConstraint:
    quoted = ", ".join(f"'{v}'" for v in values)
    return CheckConstraint(f"{column} IN ({quoted})", name=f"{column}_valid")


TENANT_PROFILES = ("restaurant", "cloud_kitchen", "central_kitchen_group", "hybrid")
TENANT_STATUSES = ("active", "suspended", "deleted")
OUTLET_TYPES = ("restaurant", "branch", "cloud_kitchen", "central_kitchen", "warehouse")
USER_STATUSES = ("active", "disabled")
MEMBERSHIP_SCOPES = ("all", "outlets")
MEMBERSHIP_STATUSES = ("active", "invited", "disabled")


class Tenant(Base):
    """FR-TEN-001. RLS: a tenant context sees only its own row (policy on id)."""

    __tablename__ = "tenants"
    __table_args__ = (
        _check_in("profile", TENANT_PROFILES),
        _check_in("status", TENANT_STATUSES),
        CheckConstraint("currency ~ '^[A-Z]{3}$'", name="currency_iso"),
        CheckConstraint("country ~ '^[A-Z]{2}$'", name="country_iso"),
    )

    id: Mapped[uuid.UUID] = _id()
    name: Mapped[str] = mapped_column(String(200))  # display name
    legal_name: Mapped[str] = mapped_column(String(200))
    country: Mapped[str] = mapped_column(String(2))
    currency: Mapped[str] = mapped_column(String(3))
    language: Mapped[str] = mapped_column(String(10))
    timezone: Mapped[str] = mapped_column(String(64))
    profile: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, server_default="active")
    created_at: Mapped[datetime] = _created_at()


class Outlet(Base):
    """FR-TEN-002."""

    __tablename__ = "outlets"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id"),  # target of composite foreign keys
        _check_in("type", OUTLET_TYPES),
        Index(None, "tenant_id", "is_active"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str] = mapped_column(String(200))
    type: Mapped[str] = mapped_column(Text)
    address: Mapped[str | None] = mapped_column(Text)
    timezone: Mapped[str] = mapped_column(String(64))
    day_cutoff: Mapped[time] = mapped_column(server_default="04:00")  # Q-015 default
    is_active: Mapped[bool] = mapped_column(server_default="true")
    created_at: Mapped[datetime] = _created_at()


class User(Base):
    """Global identity: one person can belong to several tenants (FR-IDN-005). Not
    tenant-scoped, so no RLS; only the identity service touches it (slice 0.4)."""

    __tablename__ = "users"
    __table_args__ = (_check_in("status", USER_STATUSES),)

    id: Mapped[uuid.UUID] = _id()
    email: Mapped[str] = mapped_column(CITEXT, unique=True)  # case-insensitive uniqueness
    name: Mapped[str] = mapped_column(String(200))
    password_hash: Mapped[str | None] = mapped_column(Text)  # Argon2id, slice 0.4
    totp_secret_encrypted: Mapped[bytes | None] = mapped_column()  # AES-GCM, app/core/crypto
    totp_enabled_at: Mapped[datetime | None] = mapped_column()  # NULL: set up but not confirmed
    totp_last_step: Mapped[int | None] = mapped_column(BigInteger)  # replay protection
    locale: Mapped[str] = mapped_column(String(10), server_default="id")
    status: Mapped[str] = mapped_column(Text, server_default="active")
    created_at: Mapped[datetime] = _created_at()


class Role(Base):
    """tenant_id is NULL for platform templates; tenants get their own copies (slice 0.5)."""

    __tablename__ = "roles"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id"),
        UniqueConstraint("tenant_id", "name"),
        CheckConstraint("is_template = (tenant_id IS NULL)", name="template_has_no_tenant"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str] = mapped_column(String(100))
    is_template: Mapped[bool] = mapped_column(server_default="false")
    # Members with this role must use TOTP (FR-IDN-002: owner and co-owner templates).
    requires_mfa: Mapped[bool] = mapped_column(server_default="false")
    # Which code template the role was copied from ("owner", "manager", ...); NULL for custom
    # roles. Lets the server protect the owner role (docs/03 section 6 rules 2 and 3).
    template_key: Mapped[str | None] = mapped_column(String(40))
    created_at: Mapped[datetime] = _created_at()


class RolePermission(Base):
    """tenant_id is copied from the role so RLS can apply without a join (docs/05 rule:
    every tenant-owned table carries tenant_id)."""

    __tablename__ = "role_permissions"
    __table_args__ = (
        ForeignKeyConstraint(["tenant_id", "role_id"], ["roles.tenant_id", "roles.id"]),
        UniqueConstraint("tenant_id", "role_id", "permission_code"),
        CheckConstraint(
            r"permission_code ~ '^[a-z_]+\.[a-z_]+\.[a-z_]+$'", name="permission_code_format"
        ),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID | None] = mapped_column()
    role_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("roles.id", ondelete="CASCADE"))
    permission_code: Mapped[str] = mapped_column(String(100))
    limit_value: Mapped[int | None] = mapped_column()  # e.g. max discount %, approval amount


class Membership(Base):
    __tablename__ = "memberships"
    __table_args__ = (
        UniqueConstraint("tenant_id", "id"),
        UniqueConstraint("tenant_id", "user_id"),  # one row per user per tenant
        ForeignKeyConstraint(["tenant_id", "role_id"], ["roles.tenant_id", "roles.id"]),
        _check_in("scope", MEMBERSHIP_SCOPES),
        _check_in("status", MEMBERSHIP_STATUSES),
        Index(None, "user_id"),  # "which tenants am I in" (slice 0.4)
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"))
    role_id: Mapped[uuid.UUID] = mapped_column()
    scope: Mapped[str] = mapped_column(Text, server_default="all")
    status: Mapped[str] = mapped_column(Text, server_default="active")
    created_at: Mapped[datetime] = _created_at()


class MembershipOutlet(Base):
    __tablename__ = "membership_outlets"
    __table_args__ = (
        ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(["tenant_id", "outlet_id"], ["outlets.tenant_id", "outlets.id"]),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    membership_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    outlet_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)


class AuditLog(Base):
    """FR-AUD-001/002. Append-only: UPDATE/DELETE/TRUNCATE are revoked from the app role and
    a trigger rejects them for everyone else too."""

    __tablename__ = "audit_log"
    __table_args__ = (
        Index(None, "tenant_id", "at"),
        Index(None, "tenant_id", "target_type", "target_id"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    at: Mapped[datetime] = mapped_column(server_default=func.now())
    user_id: Mapped[uuid.UUID | None] = mapped_column()
    actor_type: Mapped[str] = mapped_column(Text, server_default="user")  # user, admin, system
    outlet_id: Mapped[uuid.UUID | None] = mapped_column()
    action: Mapped[str] = mapped_column(String(100))
    target_type: Mapped[str | None] = mapped_column(String(100))
    target_id: Mapped[uuid.UUID | None] = mapped_column()
    summary: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default="{}")
    request_id: Mapped[str | None] = mapped_column(String(64))
    ip: Mapped[str | None] = mapped_column(INET)


class IdempotencyKey(Base):
    """FR-X-003 storage. Rows older than the retention window are pruned by a job."""

    __tablename__ = "idempotency_keys"
    __table_args__ = (UniqueConstraint("tenant_id", "key"),)

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    key: Mapped[uuid.UUID] = mapped_column()
    request_hash: Mapped[str] = mapped_column(String(64))
    response_status: Mapped[int | None] = mapped_column()
    response_body: Mapped[Any | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = _created_at()


class UserSession(Base):
    """Server-side session (docs/06 section 3). The cookie holds a random 256-bit token; only
    its SHA-256 hash is stored, so a database leak does not hand out live sessions.

    Not tenant-scoped: a session belongs to a user and points at the tenant currently in use
    (`active_tenant_id`), which can switch without a new sign-in (FR-IDN-005). Only the
    identity service reads this table."""

    __tablename__ = "sessions"
    __table_args__ = (
        Index(None, "user_id", "revoked_at"),
        _check_in("mfa_state", ("ok", "verify", "enroll")),
    )

    id: Mapped[uuid.UUID] = _id()
    token_hash: Mapped[bytes] = mapped_column(unique=True)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"))
    active_tenant_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("tenants.id"))
    csrf_token: Mapped[str] = mapped_column(String(64))
    # "ok": full access; "verify": password checked, TOTP code still needed; "enroll": the
    # user's role requires TOTP and none is set up yet. Only auth endpoints accept the latter two.
    mfa_state: Mapped[str] = mapped_column(Text, server_default="ok")
    created_at: Mapped[datetime] = _created_at()
    last_seen_at: Mapped[datetime] = mapped_column(server_default=func.now())
    expires_at: Mapped[datetime] = mapped_column()  # absolute timeout
    revoked_at: Mapped[datetime | None] = mapped_column()
    ip: Mapped[str | None] = mapped_column(INET)
    user_agent: Mapped[str | None] = mapped_column(String(256))


class AuthThrottle(Base):
    """Failed sign-in counters per account and per IP (FR-IDN-003). Keys are hashed so the
    table holds no email addresses or IPs in clear."""

    __tablename__ = "auth_throttle"

    key: Mapped[str] = mapped_column(String(80), primary_key=True)
    failures: Mapped[int] = mapped_column(server_default="0")
    locked_until: Mapped[datetime | None] = mapped_column()
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now())


class RecoveryCode(Base):
    """One-time 2FA recovery codes (docs/06 section 3), stored as SHA-256: the codes are long
    random strings, so a fast hash is enough (no password-style stretching needed)."""

    __tablename__ = "recovery_codes"
    __table_args__ = (Index(None, "user_id"),)

    id: Mapped[uuid.UUID] = _id()
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    code_hash: Mapped[bytes] = mapped_column(unique=True)
    used_at: Mapped[datetime | None] = mapped_column()
    created_at: Mapped[datetime] = _created_at()


class PasswordReset(Base):
    """FR-IDN-008. Single-use, short-lived; only the token hash is stored."""

    __tablename__ = "password_resets"
    __table_args__ = (Index(None, "user_id"),)

    id: Mapped[uuid.UUID] = _id()
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    token_hash: Mapped[bytes] = mapped_column(unique=True)
    expires_at: Mapped[datetime] = mapped_column()
    used_at: Mapped[datetime | None] = mapped_column()
    created_at: Mapped[datetime] = _created_at()


class Invitation(Base):
    """FR-IDN-006. Tenant-owned (RLS). Accepting happens before the invitee has a tenant
    context, so lookup by token goes through the auth_invitation_by_token() function."""

    __tablename__ = "invitations"
    __table_args__ = (
        ForeignKeyConstraint(["tenant_id", "role_id"], ["roles.tenant_id", "roles.id"]),
        Index(None, "tenant_id", "email"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    email: Mapped[str] = mapped_column(CITEXT)
    role_id: Mapped[uuid.UUID] = mapped_column()
    # NULL when the platform admin invited the first owner of a new tenant.
    invited_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    token_hash: Mapped[bytes] = mapped_column(unique=True)
    expires_at: Mapped[datetime] = mapped_column()
    used_at: Mapped[datetime | None] = mapped_column()
    created_at: Mapped[datetime] = _created_at()


class TenantModule(Base):
    """FR-TEN-003. Source of truth for which optional modules a tenant uses."""

    __tablename__ = "tenant_modules"

    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    module: Mapped[str] = mapped_column(String(40), primary_key=True)
    enabled: Mapped[bool] = mapped_column(server_default="true")
    enabled_at: Mapped[datetime] = mapped_column(server_default=func.now())


class Subscription(Base):
    """FR-SUB-001 to 005. Billing happens outside the app; the admin records the dates.
    The effective state is computed from them (app/core/access/subscription.py)."""

    __tablename__ = "subscriptions"
    __table_args__ = (_check_in("plan_type", ("free", "paid")),)

    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    plan_type: Mapped[str] = mapped_column(Text, server_default="free")
    starts_at: Mapped[datetime] = mapped_column(server_default=func.now())
    ends_at: Mapped[datetime | None] = mapped_column()  # NULL for free plans
    grace_days: Mapped[int] = mapped_column(server_default="7")
    reminders_enabled: Mapped[bool] = mapped_column(server_default="true")
    reminder_days: Mapped[list[int]] = mapped_column(ARRAY(Integer), server_default="{14,7,3,1}")
    suspended: Mapped[bool] = mapped_column(server_default="false")
    # Last state the daily job recorded; transitions are written to the audit log.
    last_state: Mapped[str | None] = mapped_column(Text)


class TenantSetting(Base):
    """FR-TEN-004 to 009: one row per setting key, validated by app/core/settings/schemas."""

    __tablename__ = "tenant_settings"

    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    key: Mapped[str] = mapped_column(String(40), primary_key=True)
    value: Mapped[dict[str, Any]] = mapped_column(JSONB)
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_by: Mapped[uuid.UUID | None] = mapped_column()


APPROVAL_DOCUMENTS = (
    "purchase_order",
    "transfer",
    "adjustment",
    "count",
    "void",
    "refund",
    "discount",
    "journal",
)


class ApprovalRule(Base):
    """FR-TEN-007: documents of this type at or above min_amount need this role's approval."""

    __tablename__ = "approval_rules"
    __table_args__ = (
        ForeignKeyConstraint(["tenant_id", "approver_role_id"], ["roles.tenant_id", "roles.id"]),
        ForeignKeyConstraint(["tenant_id", "outlet_id"], ["outlets.tenant_id", "outlets.id"]),
        _check_in("document_type", APPROVAL_DOCUMENTS),
        CheckConstraint("min_amount >= 0", name="min_amount_non_negative"),
        Index(None, "tenant_id", "document_type"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    document_type: Mapped[str] = mapped_column(Text)
    outlet_id: Mapped[uuid.UUID | None] = mapped_column()  # NULL: every outlet
    min_amount: Mapped[int] = mapped_column(BigInteger)  # minor units
    approver_role_id: Mapped[uuid.UUID] = mapped_column()
    created_at: Mapped[datetime] = _created_at()


ALERT_TYPES = (
    "below_reorder_point",
    "low_days_of_inventory",
    "batch_near_expiry",
    "expired_stock",
    "negative_stock",
    "count_variance",
    "food_cost_above_target",
    "approval_requested",
)


class AlertRule(Base):
    """FR-TEN-008: which alert goes to which role or user, on which channel."""

    __tablename__ = "alert_rules"
    __table_args__ = (
        ForeignKeyConstraint(["tenant_id", "recipient_role_id"], ["roles.tenant_id", "roles.id"]),
        _check_in("alert_type", ALERT_TYPES),
        _check_in("channel", ("in_app", "email")),
        CheckConstraint(
            "(recipient_role_id IS NULL) <> (recipient_user_id IS NULL)", name="one_recipient"
        ),
        Index(None, "tenant_id", "alert_type"),
    )

    id: Mapped[uuid.UUID] = _id()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    alert_type: Mapped[str] = mapped_column(Text)
    recipient_role_id: Mapped[uuid.UUID | None] = mapped_column()
    recipient_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    channel: Mapped[str] = mapped_column(Text, server_default="in_app")
    created_at: Mapped[datetime] = _created_at()


class NumberingCounter(Base):
    """FR-TEN-009: last number per tenant, outlet, document type and year. Allocation is one
    atomic upsert, so concurrent documents never get the same number."""

    __tablename__ = "numbering_counters"

    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    # The nil UUID means "tenant-wide" (primary key columns cannot be NULL).
    outlet_id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    doc_type: Mapped[str] = mapped_column(String(40), primary_key=True)
    year: Mapped[int] = mapped_column(primary_key=True)  # 0 when the format never resets
    last_number: Mapped[int] = mapped_column(BigInteger)
